(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.6 2017/10/25 13:27:52 verodub Exp
   ISO TC184/SC4/WG12 N9202 - ISO/TS 10303-1831 Scan data 3d shape EXPRESS MIM
*)
SCHEMA Scan_data_3d_shape_mim;

  USE FROM elemental_geometric_shape_mim;   -- ISO/TS 10303-1004
  USE FROM scan_data_3d_shape_model_schema;   -- ISO 10303-42

  REFERENCE FROM representation_schema(using_representations);   -- ISO 10303-43
END_SCHEMA;
