(*
 Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.19 2019/05/09 18:02:10 kevin Exp
 ISO TC184/SC4/WG12 N10280 - ISO/TS 10303-1128 External item identification assignment - EXPRESS MIM
*)


SCHEMA External_item_identification_assignment_mim;

USE FROM management_resources_schema   	-- ISO 10303-41
  (external_identification_assignment,
   external_identification_assignment_relationship); 

USE FROM support_resource_schema		-- ISO 10303-41
  (identifier);

TYPE external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT
	(applied_external_identification_assignment);
END_TYPE;

ENTITY applied_external_identification_assignment
SUBTYPE OF (external_identification_assignment);
  items : SET [1 : ?] OF external_identification_item;
END_ENTITY;

ENTITY applied_external_identification_assignment_relationship
	SUBTYPE of (external_identification_assignment_relationship);
	SELF\external_identification_assignment_relationship.related  : applied_external_identification_assignment;
	SELF\external_identification_assignment_relationship.relating : applied_external_identification_assignment;	
END_ENTITY;

END_SCHEMA;
