(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.12 2012/10/11 05:49:05 liutkuviene Exp
   ISO TC184/SC4/WG12 N8210 - ISO/TS 10303-1613 Physical unit non planar design view - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7605
*)


SCHEMA Physical_unit_non_planar_design_view_mim;
	USE FROM Manifold_subsurface_mim;	-- ISO/TS 10303-1702
	USE FROM Physical_unit_design_view_mim;	-- ISO/TS 10303-1728
END_SCHEMA;

