(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.6 2009/04/22 20:17:39 liutkuviene Exp
   ISO TC184/SC4/WG12 N6238 - ISO/TS 10303-1761 Information product - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4228
*)

SCHEMA Information_product_mim;

USE FROM Product_view_definition_mim;	--  ISO/TS 10303-1019
USE FROM File_identification_mim;	--  ISO/TS 10303-1127
USE FROM product_definition_schema     --  ISO 10303-41
    (product_related_product_category); 

END_SCHEMA;
