(*
   ISO TC184/SC4/WG12 N11268 - ISO/TS 10303-1844 General design connectivity - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N10954
 *)


SCHEMA General_design_connectivity_arm;

USE FROM Assembly_constraints_arm;    -- ISO/TS 10303-1794
USE FROM Design_product_data_management_arm;    -- ISO/TS 10303-1628
USE FROM Item_definition_structure_arm;    -- ISO/TS 10303-1345
USE FROM Part_shape_arm;    -- ISO/TS 10303-1807
USE FROM Shape_feature_arm;    -- ISO/TS 10303-1764

TYPE assembly_constraint_select = SELECT
  (Coaxial_assembly_constraint,
   Dimensioned_angle_assembly_constraint,
   Dimensioned_surface_distance_assembly_constraint,
   Fixed_constituent_assembly_constraint,
   Incidence_assembly_constraint,
   Parallel_assembly_constraint,
   Perpendicular_assembly_constraint,
   Tangent_assembly_constraint);
END_TYPE;

TYPE assembly_constraint_type_enumeration = EXTENSIBLE ENUMERATION OF (
	coaxial_assembly_constraint,
	complex,
	dimensioned_angle_assembly_constraint,
	dimensioned_parallel_assembly_constraint,
    dimensioned_surface_distance_assembly_constraint,
	fixed_constituent_assembly_constraint,
	incidence_assembly_constraint,
	parallel_assembly_constraint,
	perpendicular_assembly_constraint,
	tangent_assembly_constraint);
END_TYPE;

TYPE assembly_definition_or_assembly_shape_constraint = SELECT (
  Assembly_definition,
  Assembly_shape_constraint); -- to support sub-constraint
END_TYPE;

TYPE assembly_definition_or_assembly_shape_joint = SELECT (
  Assembly_definition,
  Assembly_shape_joint); -- to support sub-joints
END_TYPE;

TYPE assembly_shape_constraint_or_joint_definition_select = SELECT
   (Part_shape_element, 
    Part_shape_element_relationship,
    Shape_feature_definition,
    Shape_feature_definition_relationship,
    Shape_feature_definition_element,
    Shape_feature_definition_element_relationship);
END_TYPE; 

TYPE connected_terminal_select = SELECT
   (General_part_terminal, 
    Occurrence_terminal);
END_TYPE; 

TYPE general_assembly_joint_type_enumeration = EXTENSIBLE ENUMERATION ;
END_TYPE; 

TYPE gdc_part_shape_element_definition_select = SELECT BASED_ON part_shape_element_definition_select WITH
   (Part_shape_element_relationship,
    Occurrence_shape_element,
    Shape_feature_definition_element,
    Shape_feature_definition_element_relationship,
    Shape_feature_definition_relationship);
END_TYPE; 

TYPE general_part_terminal_associated_definition_select = EXTENSIBLE SELECT (
	Product_specification, -- added this member in order to align ARM select with DM PartTerminalElementOfSelect
	General_part_terminal, -- hierarchical
	Part_view_definition); -- terminus
END_TYPE;

TYPE general_terminal_joint_type_enumeration = EXTENSIBLE ENUMERATION; 
END_TYPE;

TYPE join_or_interface_terminal_enumeration = ENUMERATION OF (
  interface_terminal,
  join_terminal);
END_TYPE;

TYPE occurrence_contact_feature_associated_definition_select = SELECT (
	Occurrence_contact_feature, -- hierarchical
	Product_occurrence); -- terminus
END_TYPE;

TYPE occurrence_contact_feature_definition_select = SELECT
   (Occurrence_contact_feature,
    Part_contact_feature, 
    Contact_feature_definition);
END_TYPE; 

TYPE occurrence_shape_element_associated_definition_select = SELECT (
	Occurrence_shape_element, -- hierarchical
	Product_occurrence); -- terminus
END_TYPE;

TYPE occurrence_shape_element_definition_select = SELECT
   (Occurrence_shape_element, 
    Part_shape_element, 
    Shape_feature_definition);
END_TYPE; 

TYPE occurrence_shape_feature_associated_definition_select = SELECT (
	Occurrence_shape_feature, -- hierarchical
	Product_occurrence); -- terminus
END_TYPE;

TYPE occurrence_shape_feature_definition_select = SELECT
   (General_part_feature,
    Occurrence_shape_feature, 
    Shape_feature_definition);
END_TYPE; 

TYPE occurrence_terminal_associated_definition_select = SELECT (
	Occurrence_terminal, 
	Product_occurrence); 
END_TYPE;

TYPE occurrence_terminal_definition_select = SELECT
   (Contact_feature_definition,
    General_part_terminal, 
    Occurrence_terminal);
END_TYPE; 

TYPE occurrence_transport_feature_associated_definition_select = SELECT (
	Occurrence_transport_feature, -- hierarchical
	Product_occurrence); -- terminus
END_TYPE;

TYPE occurrence_transport_feature_definition_select = SELECT (
	Occurrence_transport_feature,
	Part_transport_feature);
END_TYPE;

TYPE part_contact_feature_associated_definition_select = EXTENSIBLE SELECT
   (Part_view_definition, 
    Part_contact_feature,
    Product_specification);
END_TYPE; 

TYPE part_contact_feature_definition_select = SELECT (
    Contact_feature_definition,
    Occurrence_contact_feature,
    Shape_feature_definition_element);
END_TYPE;

TYPE part_contact_feature_fit_relationship_definition_select = SELECT (
	Contact_feature_definition_fit_relationship,
	Shape_feature_definition_element_relationship);
END_TYPE;

TYPE part_feature_fit_relationship_definition_select = SELECT (
	Shape_feature_definition_fit_relationship,
	Shape_feature_definition_element_relationship);
END_TYPE;

TYPE part_transport_feature_associated_definition_select = EXTENSIBLE SELECT (
	Product_specification,  -- aligned with Domain PartTransportFeatureElementOfSelect
	Part_transport_feature, -- hierarchical
	Part_view_definition); -- terminus
END_TYPE;

TYPE part_view_definition_or_part_shape_element_or_product_specification_select = SELECT BASED_ON part_view_definition_or_part_shape_element_select WITH (
	Product_specification);
END_TYPE;

TYPE terminal_and_transport_domain_type = EXTENSIBLE ENUMERATION OF 
   (electrical,
    electrical_busbar,
    electrical_screen,
    electrical_wire,
    magnetic,
    matter,
    matter_duct,
    matter_hose,
    matter_pipe,
    multiple,
    optical,
    optical_fibre,
    thermal,
    waveguide_tube
    );
END_TYPE; 

ENTITY Assembly_shape_constraint
  SUBTYPE OF (Part_shape_element);
  SELF\Shape_element.associated_definition : assembly_definition_or_assembly_shape_constraint;
  SELF\Part_shape_element.definition : OPTIONAL assembly_shape_constraint_or_joint_definition_select;
  SELF\Shape_element.identified_item : OPTIONAL assembly_constraint_select;
  constraint_type : OPTIONAL assembly_constraint_type_enumeration;
END_ENTITY;

ENTITY Assembly_shape_constraint_item_relationship
  SUBTYPE OF (Shape_element_relationship);
  SELF\Shape_element_relationship.relating : Assembly_shape_constraint;
  SELF\Shape_element_relationship.related : Occurrence_shape_feature;
WHERE
  WR1: main_associated_definition(relating\Assembly_shape_constraint.associated_definition) 
       IN 
       main_upper_usage( main_associated_definition(related))\Product_occurrence.occurrence_contexts;
END_ENTITY;

ENTITY Assembly_shape_joint
  SUBTYPE OF (Part_shape_element);
  SELF\Shape_element.associated_definition : assembly_definition_or_assembly_shape_joint;
  SELF\Part_shape_element.definition : OPTIONAL assembly_shape_constraint_or_joint_definition_select;
  joint_type : OPTIONAL general_assembly_joint_type_enumeration;
END_ENTITY;

ENTITY Assembly_shape_joint_item_relationship
  SUBTYPE OF (Shape_element_relationship);
  SELF\Shape_element_relationship.relating : Assembly_shape_joint;
  SELF\Shape_element_relationship.related : Occurrence_shape_feature;
WHERE
  WR1: main_associated_definition(relating\Assembly_shape_joint.associated_definition) 
       IN 
       main_upper_usage( main_associated_definition(related))\Product_occurrence.occurrence_contexts;
END_ENTITY;

ENTITY Contact_feature_definition
  SUBTYPE OF (Shape_feature_definition);
END_ENTITY;

ENTITY Contact_feature_definition_fit_relationship
  SUBTYPE OF (Shape_feature_definition_fit_relationship);
  SELF\Shape_feature_definition_relationship.relating : Contact_feature_definition;
  SELF\Shape_feature_definition_relationship.related : Contact_feature_definition;
  joint_type : OPTIONAL general_assembly_joint_type_enumeration;
END_ENTITY;

ENTITY General_part_terminal
  SUBTYPE OF (Part_contact_feature);
  SELF\Shape_element.associated_definition : general_part_terminal_associated_definition_select;
  associated_transport_feature : OPTIONAL Part_transport_feature;
  intended_joint_type : OPTIONAL SET [1:?] OF general_terminal_joint_type_enumeration;
  join_or_interface_terminal : OPTIONAL join_or_interface_terminal_enumeration;
  domain_type : OPTIONAL terminal_and_transport_domain_type;
WHERE
  WR1: main_associated_definition(SELF) :=: main_associated_definition(associated_transport_feature);
  WR2: domain_type :=: associated_transport_feature.domain_type; 
END_ENTITY;

ENTITY Occurrence_contact_feature
  SUPERTYPE OF (Occurrence_terminal)
  SUBTYPE OF (Occurrence_shape_feature);
  SELF\Shape_element.associated_definition : occurrence_contact_feature_associated_definition_select;
  SELF\Occurrence_shape_feature.definition : OPTIONAL occurrence_contact_feature_definition_select;
END_ENTITY;

ENTITY Occurrence_shape_element
  SUBTYPE OF (Shape_element);
  SELF\Shape_element.associated_definition : occurrence_shape_element_associated_definition_select;
  definition : OPTIONAL occurrence_shape_element_definition_select;
UNIQUE
  UR1: definition, associated_definition;
  UR2: SELF\Shape_element.element_name, associated_definition;
WHERE
  WR1: acyclic_occurrence_shape_element(SELF,definition);
END_ENTITY;

ENTITY Occurrence_shape_feature
  SUPERTYPE OF (ONEOF (Occurrence_contact_feature,
                       Occurrence_transport_feature))
  SUBTYPE OF (Occurrence_shape_element);
  SELF\Shape_element.associated_definition : occurrence_shape_feature_associated_definition_select;
  SELF\Occurrence_shape_element.definition : OPTIONAL occurrence_shape_feature_definition_select;
DERIVE
  SELF\Shape_element.product_definitional : BOOLEAN := TRUE;
END_ENTITY;

ENTITY Occurrence_terminal
  SUBTYPE OF (Occurrence_contact_feature);
  SELF\Shape_element.associated_definition : occurrence_terminal_associated_definition_select;
  SELF\Occurrence_shape_element.definition : OPTIONAL occurrence_terminal_definition_select;
  associated_transport_feature : OPTIONAL Occurrence_transport_feature;
WHERE
  WR1: main_associated_definition(associated_transport_feature.associated_definition) :=: main_associated_definition(associated_definition);
END_ENTITY;

ENTITY Occurrence_transport_feature
  SUBTYPE OF (Occurrence_shape_feature);
  SELF\Shape_element.associated_definition : occurrence_transport_feature_associated_definition_select;
  SELF\Occurrence_shape_element.definition : OPTIONAL occurrence_transport_feature_definition_select;
  domain_type : OPTIONAL terminal_and_transport_domain_type;
END_ENTITY;

ENTITY Part_connectivity_definition
  SUBTYPE OF (Part_shape_element);
  connected_terminals : SET[2:?] OF connected_terminal_select;
WHERE
  WR1: terminal_usage_check( main_associated_definition(SELF\Part_shape_element.associated_definition), connected_terminals);
END_ENTITY;

ENTITY Part_contact_feature
  SUBTYPE OF (General_part_feature);
  SELF\Shape_element.associated_definition : part_contact_feature_associated_definition_select;
  SELF\Part_shape_element.definition : OPTIONAL part_contact_feature_definition_select;
END_ENTITY;

ENTITY Part_contact_feature_fit_relationship
  SUBTYPE OF (Part_feature_fit_relationship);
  SELF\Shape_element_relationship.related : Part_contact_feature;
  SELF\Shape_element_relationship.relating : Part_contact_feature;
  SELF\Part_feature_fit_relationship.definition : OPTIONAL part_contact_feature_fit_relationship_definition_select;
  parent_relationship : OPTIONAL Part_contact_feature_fit_relationship;
WHERE
	WR1: ((related.definition :=: definition\Shape_feature_definition_relationship.related)
	   OR (related.definition :=: definition\Shape_feature_definition_element_relationship.related))
	AND  ((relating.definition :=: definition\Shape_feature_definition_relationship.relating)
	   OR (relating.definition :=: definition\Shape_feature_definition_element_relationship.relating));
	WR2: (related.associated_definition :=: parent_relationship.related)
	 AND (relating.associated_definition :=: parent_relationship.relating);
END_ENTITY;

ENTITY Part_feature_fit_relationship
  SUBTYPE OF (Part_shape_element_relationship);
  SELF\Shape_element_relationship.related : General_part_feature;
  SELF\Shape_element_relationship.relating : General_part_feature;
  definition : OPTIONAL part_feature_fit_relationship_definition_select;
END_ENTITY;

ENTITY Part_transport_feature
  SUBTYPE OF (General_part_feature);
  SELF\Shape_element.associated_definition : part_transport_feature_associated_definition_select;
  domain_type : OPTIONAL terminal_and_transport_domain_type;
END_ENTITY;

ENTITY Shape_feature_definition_fit_relationship
  SUBTYPE OF (Shape_feature_definition_relationship);
END_ENTITY;

FUNCTION acyclic_occurrence_shape_element
          (sao : Occurrence_shape_element; definition : occurrence_shape_element_definition_select) : BOOLEAN;
    IF NOT (('GENERAL_DESIGN_CONNECTIVITY_ARM.OCCURRENCE_SHAPE_ELEMENT') IN TYPEOF(definition)) THEN
      RETURN  (TRUE);
    END_IF;
    IF  (definition :=: sao) THEN
      RETURN  (FALSE);
    ELSE 
      RETURN(acyclic_occurrence_shape_element(sao, definition\Occurrence_shape_element.definition));
    END_IF;
END_FUNCTION; 

FUNCTION acyclic_shape_element
          (se : Shape_element; associated_definition : occurrence_shape_element_definition_select) : BOOLEAN;
    IF NOT (('SHAPE_PROPERTY_ASSIGNMENT_ARM.SHAPE_ELEMENT') IN TYPEOF(associated_definition)) THEN
      RETURN  (TRUE);
    END_IF;
    IF  (associated_definition :=: se) THEN
      RETURN  (FALSE);
    ELSE 
      RETURN(acyclic_shape_element(se, associated_definition\Shape_element.associated_definition));
    END_IF;
END_FUNCTION; 

FUNCTION main_associated_definition(se : shapeable_item) : shapeable_item;
    IF NOT ('SHAPE_PROPERTY_ASSIGNMENT_ARM.SHAPE_ELEMENT' IN TYPEOF(se)) THEN
    	RETURN (se);
    ELSE
	    IF NOT ('SHAPE_PROPERTY_ASSIGNMENT_ARM.SHAPE_ELEMENT' IN TYPEOF(se.associated_definition)) THEN
	    	RETURN  (se.associated_definition);
	    ELSE 
  	    	RETURN(main_associated_definition(se.associated_definition));
	    END_IF;
    END_IF;
END_FUNCTION; 

FUNCTION main_upper_usage(po : Product_occurrence) : Product_occurrence;
    IF NOT (('PRODUCT_OCCURRENCE_ARM.SPECIFIED_OCCURRENCE') IN TYPEOF(po)) THEN
      RETURN  (po);
    ELSE 
      RETURN(main_upper_usage(po\Specified_occurrence.upper_usage));
    END_IF;
END_FUNCTION; 

FUNCTION terminal_usage_check(p: Part_view_definition; terminals: SET OF connected_terminal_select) : BOOLEAN;
	REPEAT i := 1 TO HIINDEX(terminals) BY 1;
		IF 'GENERAL_DESIGN_CONNECTIVITY_ARM.GENERAL_PART_TERMINAL' IN TYPEOF(terminals[i]) THEN
			IF p :<>: terminals[i]\General_part_terminal.associated_definition THEN
				RETURN(FALSE);
			END_IF;
		ELSE 
			IF 'GENERAL_DESIGN_CONNECTIVITY_ARM.OCCURRENCE_TERMINAL' IN TYPEOF(terminals[i]) THEN
				IF NOT(p = main_upper_usage( main_associated_definition(terminals[i]))) THEN 
				-- Should there be a test for p being a Product_occurrence?
					RETURN(FALSE);
				END_IF;
			ELSE
				RETURN (FALSE);
			END_IF;
		END_IF;
	END_REPEAT;
	RETURN(TRUE); 
END_FUNCTION; 

RULE shape_elements_are_acyclic FOR (Shape_element);
WHERE
  WR1: SIZEOF(QUERY(se <* Shape_element | NOT acyclic_shape_element(se, se.associated_definition) )) = 0;
END_RULE;

SUBTYPE_CONSTRAINT gdc_general_part_feature_subtypes FOR General_part_feature;
  ONEOF (Part_transport_feature,
         Part_contact_feature);
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT gdc_part_shape_element_subtypes FOR Part_shape_element;
  ONEOF (Assembly_shape_constraint,
         Assembly_shape_joint,
         Part_connectivity_definition);
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT gdc_shape_element_subtypes FOR Shape_element;
  ONEOF (Occurrence_shape_element,
         Part_shape_element,
         Shape_feature_definition_element);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;  -- General_design_connectivity_arm
