(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.3 2012/10/11 05:49:26 liutkuviene Exp
   ISO TC184/SC4/WG12 N7808 - ISO/TS 10303-1521 Product data quality criteria - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7179
*)
SCHEMA Product_data_quality_criteria_mim;

  USE FROM Foundation_representation_mim;

  USE FROM Product_data_quality_inspection_result_mim;

  USE FROM Product_data_quality_criteria_schema;

END_SCHEMA;
