(*
   Part1000: $Id: $
 STEPmod.CVS.Id: arm.exp,v 1.4 2019/02/18 02:22:07 ftanaka Exp
   ISO TC184/SC4/WG12 N9971 - ISO/TS 10303-1841 annotated_3d_model_equivalence_assembly - EXPRESS ARM
*)

SCHEMA Annotated_3d_model_equivalence_assembly_arm;

  USE FROM Annotated_3d_model_equivalence_shape_arm;	--  ISO/TS 10303-1840

  USE FROM Assembly_constraints_arm;	--  ISO/TS 10303-1794

  USE FROM Contextual_shape_positioning_arm;	--  ISO/TS 10303-1027

  REFERENCE FROM Support_resource_arm 	--  ISO/TS 10303-1800
    (bag_to_set);

  TYPE a3ma_accuracy_type_name = EXTENSIBLE ENUMERATION BASED_ON a3m_accuracy_type_name WITH
    (atna_others);
  END_TYPE;

  TYPE a3ma_detected_difference_type_name = EXTENSIBLE ENUMERATION BASED_ON a3m_detected_difference_type_name WITH
    (ddna_a3ms_inspected_equivalence_element_select,
     ddna_assembly_component_relationship,
     ddna_binary_assembly_constraint,
     ddna_cartesian_point,
     ddna_contextual_shape_representation,
     ddna_count_measure,
     ddna_multi_level_reference_designator,
     ddna_no_element,
     ddna_others,
     ddna_volume_measure);
  END_TYPE;
  
  TYPE a3ma_element_type_name = EXTENSIBLE ENUMERATION BASED_ON a3m_element_type_name WITH
    (etna_geometric_model,
     etna_product_view_definition_or_reference,
     etna_others);
  END_TYPE;
  
  TYPE a3ma_equivalence_detected_difference_select = EXTENSIBLE SELECT 
    BASED_ON equivalence_detected_difference_select WITH
    (a3ms_inspected_equivalence_element_select,
     Assembly_component_relationship,
     Binary_assembly_constraint,
     Cartesian_point,
     Contextual_shape_representation,
     count_measure,
     Multi_level_reference_designator,
     volume_measure);
  END_TYPE;

  TYPE a3ma_equivalence_measured_value_select = EXTENSIBLE SELECT 
    BASED_ON equivalence_measured_value_select WITH
    (A3ma_length_measure_and_any_number_pair,
     any_number_value,
	 length_measure,
     plane_angle_measure,
     volume_measure);
  END_TYPE;
  
  TYPE a3ma_inspected_equivalence_element_select = EXTENSIBLE GENERIC_ENTITY SELECT 
    BASED_ON inspected_equivalence_element_select WITH
    (Geometric_model,
     product_view_definition_or_reference);
  END_TYPE;

  TYPE a3ma_measured_data_type_name = EXTENSIBLE ENUMERATION BASED_ON a3m_measured_data_type_name WITH
    (mdna_any_number_value,
     mdna_boolean_value,
     mdna_length_measure,
     mdna_length_measure_and_any_number_value,
     mdna_others,
     mdna_plane_angle_measure,
     mdna_volume_measure);
  END_TYPE;

  TYPE a3ma_target_annotated_3d_model_select = EXTENSIBLE GENERIC_ENTITY SELECT 
    BASED_ON target_annotated_3d_model_select WITH
    (Geometric_model_relationship);
  END_TYPE;

  ENTITY A3m_equivalence_criterion_for_assembly
    ABSTRACT SUPERTYPE OF 
      (ONEOF(A3m_equivalence_criterion_of_assembly_data_structure,
             A3m_equivalence_criterion_of_detailed_assembly_data_content,
             A3m_equivalence_criterion_of_component_property_difference,
             A3m_equivalence_criterion_of_representative_assembly_property_value))
    SUBTYPE OF(A3m_equivalence_criterion);
      SELF\A3m_equivalence_criterion.comparing_element_types : LIST[1:?] OF a3ma_element_type_name;
      SELF\A3m_equivalence_criterion.compared_element_types : LIST[1:?] OF a3ma_element_type_name;
      SELF\A3m_equivalence_criterion.measured_data_type : a3ma_measured_data_type_name;
      SELF\A3m_equivalence_criterion.detected_difference_types : LIST[1:?] OF a3ma_detected_difference_type_name;
    DERIVE
      SELF\A3m_equivalence_criterion.accuracy_types : LIST[0:0] OF a3ma_accuracy_type_name := [];  
    WHERE
      WR1: a3ma_validate_accuracy_types(SELF,SELF);
   END_ENTITY;

  ENTITY A3m_equivalence_criterion_of_assembly_data_structure
    ABSTRACT SUPERTYPE OF
     (ONEOF  (Different_component_identification_via_multi_level_reference,
              Mismatch_of_component,
              Missing_assembly_constraint,
              Missing_component))
    SUBTYPE OF(A3m_equivalence_criterion_for_assembly);
    DERIVE
      SELF\A3m_equivalence_criterion.comparing_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
      SELF\A3m_equivalence_criterion.compared_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
  END_ENTITY;
  
  ENTITY A3m_equivalence_criterion_of_component_property_difference
    ABSTRACT SUPERTYPE OF
     (Different_component_shape)
    SUBTYPE OF(A3m_equivalence_criterion_for_assembly);
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
  END_ENTITY;

  ENTITY A3m_equivalence_criterion_of_detailed_assembly_data_content
    ABSTRACT SUPERTYPE OF
     (ONEOF  (Different_angle_of_assembly_constraint,
			  Different_assembly_constraint_type,
     		  Different_component_type,
              Different_length_of_assembly_constraint,
              Different_placement_of_component))
    SUBTYPE OF(A3m_equivalence_criterion_for_assembly);
    DERIVE
      SELF\A3m_equivalence_criterion.comparing_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
      SELF\A3m_equivalence_criterion.compared_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
  END_ENTITY;
     
  ENTITY A3m_equivalence_criterion_of_representative_assembly_property_value
    ABSTRACT SUPERTYPE OF
     (ONEOF  (Different_assembly_centroid,
              Different_assembly_centroid_using_notional_solid,
              Different_assembly_volume,
              Different_number_of_components))
    SUBTYPE OF(A3m_equivalence_criterion_for_assembly);
    DERIVE
      SELF\A3m_equivalence_criterion.comparing_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
      SELF\A3m_equivalence_criterion.compared_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_product_view_definition_or_reference];
  END_ENTITY;
  
  ENTITY A3m_equivalence_inspection_result_representation_for_assembly
    SUBTYPE OF(A3m_equivalence_inspection_result_representation);
    WHERE
      WR1 : SIZEOF( QUERY( q <* SELF\Representation.items|
                                'ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3MS_EQUIVALENCE_INSPECTION_RESULT'
                                 IN TYPEOF(q))) = 0;
  END_ENTITY;

  ENTITY A3m_equivalence_inspection_result_representation_for_shape
    SUBTYPE OF(A3m_equivalence_inspection_result_representation);
    WHERE
      WR1 : SIZEOF( QUERY( q <* SELF\Representation.items|
                                'ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3MA_EQUIVALENCE_INSPECTION_RESULT'
                                 IN TYPEOF(q))) = 0;
  END_ENTITY;
  
  ENTITY A3ma_equivalence_inspection_result
    SUBTYPE OF(A3m_equivalence_inspection_result);
      SELF\A3m_equivalence_inspection_result.criterion_inspected:A3m_equivalence_criterion_for_assembly;
    WHERE
     WR1: a3ma_validate_accuracy_types(SELF,
           SELF\A3m_equivalence_inspection_result.criterion_inspected);
     WR2: SIZEOF (QUERY(re <* bag_to_set(USEDIN(SELF,
           'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.A3M_EQUIVALENCE_INSPECTION_REPORT.INSPECTION_RESULT')) |
         NOT(a3ma_validate_element_types(re,
             SELF\A3m_equivalence_inspection_result.criterion_inspected)))) = 0;
     WR3: SIZEOF (QUERY(re <* bag_to_set(USEDIN(SELF,
           'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.A3M_EQUIVALENCE_INSPECTION_REPORT.INSPECTION_RESULT')) |
         NOT(a3ma_validate_detected_difference_types(re,
             SELF\A3m_equivalence_inspection_result.criterion_inspected)))) = 0;
     WR4: SIZEOF (QUERY(re <* bag_to_set(USEDIN(SELF,
           'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.A3M_EQUIVALENCE_INSPECTION_REPORT.INSPECTION_RESULT')) |
         NOT(a3ma_validate_measured_type(re,
             SELF\A3m_equivalence_inspection_result.criterion_inspected)))) = 0;
  END_ENTITY;

  ENTITY A3ma_length_measure_and_any_number_pair
    SUBTYPE OF (Representation_item);
	  length_value : length_measure;
	  number_value : any_number_value;
  END_ENTITY;

  ENTITY Different_angle_of_assembly_constraint
    SUBTYPE OF(A3m_equivalence_criterion_of_detailed_assembly_data_content);  
       SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_plane_angle_measure;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_binary_assembly_constraint];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = SELF.measured_data_type);
  END_ENTITY;

  ENTITY Different_assembly_centroid
    SUBTYPE OF(A3m_equivalence_criterion_of_representative_assembly_property_value);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_length_measure;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_cartesian_point];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = SELF.measured_data_type);
  END_ENTITY;

   ENTITY Different_assembly_centroid_using_notional_solid
    SUBTYPE OF(A3m_equivalence_criterion_of_representative_assembly_property_value);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_length_measure;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_cartesian_point];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = SELF.measured_data_type);
  END_ENTITY;

  ENTITY Different_assembly_constraint_type
    SUBTYPE OF(A3m_equivalence_criterion_of_detailed_assembly_data_content);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_binary_assembly_constraint];
  END_ENTITY;

  ENTITY Different_assembly_volume
    SUBTYPE OF(A3m_equivalence_criterion_of_representative_assembly_property_value);  
       SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_volume_measure;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_volume_measure];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = SELF.measured_data_type);
  END_ENTITY;
  
  ENTITY Different_component_identification_via_multi_level_reference
    SUBTYPE OF(A3m_equivalence_criterion_of_assembly_data_structure);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_multi_level_reference_designator];
  END_ENTITY;

  ENTITY Different_component_shape
    SUBTYPE OF(A3m_equivalence_criterion_of_component_property_difference);  
      shape_criteria : SET [1:?] OF A3m_equivalence_criterion_for_shape;
    DERIVE
      SELF\A3m_equivalence_criterion.comparing_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_geometric_model];
      SELF\A3m_equivalence_criterion.compared_element_types :  LIST[1:1] OF a3ma_element_type_name := [etna_geometric_model];
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_a3ms_inspected_equivalence_element_select];
  END_ENTITY;

  ENTITY Different_component_type
    SUBTYPE OF(A3m_equivalence_criterion_of_detailed_assembly_data_content);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_assembly_component_relationship];
  END_ENTITY;
  
  ENTITY Different_length_of_assembly_constraint
    SUBTYPE OF(A3m_equivalence_criterion_of_detailed_assembly_data_content);  
       SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_length_measure;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_binary_assembly_constraint];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = SELF.measured_data_type);
  END_ENTITY;

  ENTITY Different_number_of_components
    SUBTYPE OF(A3m_equivalence_criterion_of_representative_assembly_property_value);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_count_measure];
  END_ENTITY;

  ENTITY Different_placement_of_component
    SUBTYPE OF(A3m_equivalence_criterion_of_detailed_assembly_data_content);  
       SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_numerical_test;
       assessment_threshold_2 : A3m_equivalence_lower_value_limit;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_length_measure_and_any_number_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_contextual_shape_representation];
    WHERE
      WR1 : ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_LOWER_VALUE_LIMIT' 
              IN TYPEOF(SELF\A3m_equivalence_criterion.assessment_specification\
                           A3m_equivalence_assessment_by_numerical_test.threshold)) AND
            (a3ma_get_value_limit_type(SELF\A3m_equivalence_criterion.assessment_specification\A3m_equivalence_assessment_by_numerical_test.threshold)
             = mdna_length_measure);
      WR2 :  (a3ma_get_value_limit_type(SELF.assessment_threshold_2) = mdna_any_number_value) AND
             ('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.CONTEXT_DEPENDENT_UNIT' IN
             TYPEOF(SELF.assessment_threshold_2\Value_with_unit.unit));
  END_ENTITY;

  ENTITY Mismatch_of_component
    SUBTYPE OF(A3m_equivalence_criterion_of_assembly_data_structure);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[1:1] OF a3ma_detected_difference_type_name
       := [ddna_assembly_component_relationship];
  END_ENTITY;

  ENTITY Missing_assembly_constraint
    SUBTYPE OF(A3m_equivalence_criterion_of_assembly_data_structure);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[2:2] OF a3ma_detected_difference_type_name
       := [ddna_no_element, ddna_binary_assembly_constraint];
  END_ENTITY;

  ENTITY Missing_component
    SUBTYPE OF(A3m_equivalence_criterion_of_assembly_data_structure);  
      SELF\A3m_equivalence_criterion.assessment_specification : A3m_equivalence_assessment_by_logical_test;
    DERIVE
      SELF\A3m_equivalence_criterion.measured_data_type: a3ma_measured_data_type_name := mdna_boolean_value;
      SELF\A3m_equivalence_criterion.detected_difference_types: LIST[2:2] OF a3ma_detected_difference_type_name
       := [ddna_no_element, ddna_assembly_component_relationship];
  END_ENTITY;

  FUNCTION a3ma_get_accuracy_types
    (ei:SET [0:?] OF A3m_equivalence_accuracy_association): SET [0:?] OF a3ma_accuracy_type_name;
    LOCAL
      type_out :a3ma_measured_data_type_name;
      retval : SET OF a3ma_accuracy_type_name := [];
    END_LOCAL;
    REPEAT i:= 1 TO SIZEOF(ei);
      type_out := a3ma_get_value_limit_type(ei[i].specific_accuracy.range);
      retval := retval + [atna_others];         
    END_REPEAT;
    RETURN(retval);
  END_FUNCTION;
  
  FUNCTION a3ma_get_detected_difference_type
    (ei:LIST [0:?] OF equivalence_detected_difference_select):a3ma_detected_difference_type_name;
    LOCAL
      type_out : SET OF STRING;
      sizeei : INTEGER;
    END_LOCAL;
    sizeei := SIZEOF(ei); 
    IF(sizeei = 0) THEN
      RETURN(ddna_no_element);
    END_IF;
    IF(sizeei > 1) THEN
      RETURN(ddna_others);
    ELSE
       type_out := TYPEOF(ei[1]);
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.ASSEMBLY_COMPONENT_RELATIONSHIP' IN type_out) THEN
         RETURN(ddna_assembly_component_relationship);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.BINARY_ASSEMBLY_CONSTRAINT' IN type_out) THEN
         RETURN(ddna_binary_assembly_constraint);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.CARTESIAN_POINT' IN type_out) THEN
         RETURN(ddna_cartesian_point);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.CONTEXTUAL_SHAPE_REPRESENTATION' IN type_out) THEN
         RETURN(ddna_contextual_shape_representation);
       END_IF;
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.COUNT_MEASURE' IN type_out) THEN
         RETURN(ddna_count_measure);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.MULTI_LEVEL_REFERENCE_DESIGNATOR' IN type_out) THEN
         RETURN(ddna_multi_level_reference_designator);
       END_IF;
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.VOLUME_MEASURE' IN type_out) THEN
         RETURN(ddna_volume_measure);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT' IN type_out) THEN
         RETURN(ddna_a3ms_inspected_equivalence_element_select);
       END_IF;
     END_IF;
    RETURN(ddna_others);
  END_FUNCTION;

  FUNCTION a3ma_get_element_type
    (ei:SET[1:?] OF inspected_equivalence_element_select):a3ma_element_type_name;
    LOCAL
      type_out : SET OF STRING;
    END_LOCAL;
    IF(SIZEOF(ei) <> 1) THEN
      RETURN(etna_others);
    ELSE
       type_out := TYPEOF(ei[1]);
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.GEOMETRIC_MODEL' IN type_out) THEN
         RETURN(etna_geometric_model);
       END_IF;
       IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.PRODUCT_VIEW_DEFINITION_OR_REFERENCE' IN type_out) THEN
         RETURN(etna_product_view_definition_or_reference);
       END_IF;
    END_IF;
    RETURN(etna_others);
  END_FUNCTION;

  FUNCTION a3ma_get_measured_type
    (ei: equivalence_measured_value_select):a3ma_measured_data_type_name;
    LOCAL
    type_out : SET OF STRING;
    END_LOCAL;
    type_out := TYPEOF(ei);
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.ANY_NUMBER_VALUE' IN type_out) THEN
       RETURN(mdna_any_number_value);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.EQUIVALENCE_BOOLEAN_VALUE' IN type_out) THEN
       RETURN(mdna_boolean_value);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.LENGTH_MEASURE' IN type_out) THEN
       RETURN(mdna_length_measure);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3MA_LENGTH_MEASURE_AND_ANY_NUMBER_PAIR' IN type_out) THEN
       RETURN(mdna_length_measure_and_any_number_value);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.PLANE_ANGLE_MEASURE' IN type_out) THEN
       RETURN(mdna_plane_angle_measure);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.VOLUME_MEASURE' IN type_out) THEN
       RETURN(mdna_volume_measure);
    END_IF;
    RETURN(mdna_others);
  END_FUNCTION;

  FUNCTION a3ma_get_value_limit_type
    (ei:a3m_equivalence_value_limit_type_select):a3ma_measured_data_type_name;
    LOCAL
      aevr : A3m_equivalence_value_range;
      aevl : A3m_equivalence_value_limit;
      type_out : SET OF STRING :=[];
    END_LOCAL;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_VALUE_RANGE' IN TYPEOF(ei)) THEN
      aevr := ei;
      type_out := TYPEOF (aevr.lower_limit.value_component);
    ELSE
      IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_VALUE_LIMIT' IN TYPEOF(ei)) THEN
        aevl := ei;
        type_out := TYPEOF (aevl.value_component);
      END_IF;
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.ANY_NUMBER_VALUE' IN type_out) THEN
       RETURN(mdna_any_number_value);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.LENGTH_MEASURE' IN type_out) THEN
       RETURN(mdna_length_measure);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.PLANE_ANGLE_MEASURE' IN type_out) THEN
       RETURN(mdna_plane_angle_measure);
    END_IF;
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.VOLUME_MEASURE' IN type_out) THEN
       RETURN(mdna_volume_measure);
    END_IF;
    RETURN(mdna_others);
  END_FUNCTION;

  FUNCTION a3ma_validate_accuracy_types
    (aats:accuracy_associated_target_select;
     cr:A3m_equivalence_criterion_for_assembly):LOGICAL;
    LOCAL
      aeaa : SET OF A3m_equivalence_accuracy_association;
      rp :  SET OF Representation;
      tp : SET OF a3ma_accuracy_type_name := [];
    END_LOCAL;
    REPEAT i:= 1 TO SIZEOF(cr.accuracy_types);
      tp := tp + [cr.accuracy_types[i]];
    END_REPEAT;
    -- aats is rep_item
    IF( 'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.REPRESENTATION_ITEM' IN TYPEOF(aats)) THEN
       -- specific accuracy
       aeaa := bag_to_set(USEDIN(aats,
            'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.A3M_EQUIVALENCE_ACCURACY_ASSOCIATION.EQUIVALENCE_TARGET'));
       IF(SIZEOF(cr.accuracy_types) = 0) THEN
          IF(SIZEOF(aeaa) = 0) THEN
             RETURN(TRUE);
          ELSE
		     RETURN(FALSE);
          END_IF;
       END_IF;
       IF(a3ma_get_accuracy_types(aeaa) = tp) THEN
	      RETURN(TRUE);
       END_IF;
       -- global accuracy
       rp := bag_to_set(USEDIN(aats,
              'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.REPRESENTATION.ITEMS'));
    ELSE
      IF( 'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.REPRESENTATION' IN TYPEOF(aats)) THEN
         rp := [aats];
      ELSE
         rp := [];
      END_IF;
    END_IF;
    -- global accuracy check
    aeaa := [];
    REPEAT i:= 1 TO SIZEOF(rp);
	  aeaa := aeaa + bag_to_set(USEDIN(rp[i],
           'ANNOTATED_3D_MODEL_EQUIVALENCE_INSPECTION_RESULT_ARM.A3M_EQUIVALENCE_ACCURACY_ASSOCIATION.EQUIVALENCE_TARGET'));
    END_REPEAT;
    IF(a3ma_get_accuracy_types(aeaa) >= tp) THEN
	  RETURN(TRUE);
    END_IF;
    RETURN(FALSE);
  END_FUNCTION;

  FUNCTION a3ma_validate_detected_difference_types
    (ei:A3m_equivalence_inspection_report;
     cr:A3m_equivalence_criterion_for_assembly):LOGICAL;
    LOCAL
      aeiir : A3m_equivalence_inspection_instance_report;
      eiriwei : Equivalence_instance_report_item_with_notable_instances;
      addtn : a3ma_detected_difference_type_name;     
    END_LOCAL;
     -- A3m_equivalence_inspection_instance_report
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_INSTANCE_REPORT' IN TYPEOF(ei)) THEN
      aeiir := ei;
      REPEAT i := 1 TO SIZEOF(aeiir.inspected_instances);
    --   >     Equivalence_notable_instance
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.EQUIVALENCE_INSTANCE_REPORT_ITEM_WITH_NOTABLE_INSTANCES'
           IN TYPEOF(aeiir.inspected_instances[i])) THEN
           eiriwei := aeiir.inspected_instances[i];
           REPEAT j := 1 TO SIZEOF(eiriwei.notable_instances);
            IF(NOT(a3ma_get_detected_difference_type(
                       eiriwei.notable_instances[j].comparing_elements)
                    IN cr.detected_difference_types)) THEN
			    RETURN(FALSE);
			END_IF;     
            IF(NOT(a3ma_get_detected_difference_type(
                       eiriwei.notable_instances[j].compared_elements)
                    IN cr.detected_difference_types)) THEN
			    RETURN(FALSE);
			END_IF;
           END_REPEAT;
        END_IF;
      END_REPEAT;
    END_IF;
    RETURN(TRUE);     
  END_FUNCTION;

  FUNCTION a3ma_validate_element_types
    (ei:A3m_equivalence_inspection_report;
     cr:A3m_equivalence_criterion_for_assembly):LOGICAL;
    LOCAL
      aeiir : A3m_equivalence_inspection_instance_report;
      aeiiri : A3m_equivalence_inspection_instance_report_item;
      aeiep : A3m_equivalence_inspected_element_pair;
      compared_et:a3ma_element_type_name;
      comparing_et:a3ma_element_type_name;
    END_LOCAL;
    -- A3m_equivalence_inspection_instance_report
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_INSTANCE_REPORT' IN TYPEOF(ei)) THEN
      aeiir := ei;
      REPEAT i := 1 TO SIZEOF(aeiir.inspected_instances);
    --   > A3m_equivalence_inspection_instance_report_item
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_INSTANCE_REPORT_ITEM'
           IN TYPEOF(aeiir.inspected_instances[i])) THEN
           aeiiri := aeiir.inspected_instances[i];
           aeiep := aeiiri.inspected_element;
           compared_et := a3ma_get_element_type(aeiep.compared_elements);
           comparing_et := a3ma_get_element_type(aeiep.comparing_elements);
           IF(NOT(compared_et IN cr.compared_element_types) OR
              NOT(comparing_et IN cr.comparing_element_types)) THEN
             RETURN(FALSE);
           END_IF;
	   	   IF(compared_et <> comparing_et) THEN
               RETURN(FALSE);
           END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
    RETURN(TRUE);
  END_FUNCTION;

  FUNCTION a3ma_validate_measured_type
    (ei:A3m_equivalence_inspection_report;
     cr:A3m_equivalence_criterion_for_assembly):LOGICAL;
    LOCAL
      aeicr : A3m_equivalence_inspection_criterion_report;
      aeiir : A3m_equivalence_inspection_instance_report;
      aeiiri : A3m_equivalence_inspection_instance_report_item;
      amdtn : a3ma_measured_data_type_name;
      criwmv : Criterion_report_item_with_measured_value;
      eiriwei : Equivalence_instance_report_item_with_notable_instances;
    END_LOCAL;
    amdtn := cr.measured_data_type;
    -- A3m_equivalence_inspection_criterion_report
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_CRITERION_REPORT' IN TYPEOF(ei)) THEN
      aeicr := ei;
      REPEAT i := 1 TO SIZEOF(aeicr.statistical_values);
    -- Criterion_report_item_with_measured_value.representative_measured_value
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.CRITERION_REPORT_ITEM_WITH_MEASURED_VALUE'
           IN TYPEOF(aeicr.statistical_values[i])) THEN
           criwmv := aeicr.statistical_values[i];
           IF(a3ma_get_measured_type(criwmv.representative_measured_value) <> amdtn) THEN
             RETURN(FALSE);
           END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
    -- A3m_equivalence_inspection_instance_report
    IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_INSTANCE_REPORT' IN TYPEOF(ei)) THEN
      aeiir := ei;
      REPEAT i := 1 TO SIZEOF(aeiir.inspected_instances);
    --   > A3m_equivalence_inspection_instance_report_item.measured_value_for_inspected_element
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.A3M_EQUIVALENCE_INSPECTION_INSTANCE_REPORT_ITEM'
           IN TYPEOF(aeiir.inspected_instances[i])) THEN
           aeiiri := aeiir.inspected_instances[i];
           IF(a3ma_get_measured_type(aeiiri.measured_value_for_inspected_element) <> amdtn) THEN
             RETURN(FALSE);
           END_IF;
        END_IF;
    --   >     Equivalence_notable_instance.measured_value
        IF('ANNOTATED_3D_MODEL_EQUIVALENCE_ASSEMBLY_ARM.EQUIVALENCE_INSTANCE_REPORT_ITEM_WITH_NOTABLE_INSTANCES'
           IN TYPEOF(aeiir.inspected_instances[i])) THEN
           eiriwei := aeiir.inspected_instances[i];
           REPEAT j := 1 TO SIZEOF(eiriwei.notable_instances);
             IF(a3ma_get_measured_type(eiriwei.notable_instances[j].measured_value) <> amdtn) THEN
               RETURN(FALSE);
             END_IF;
           END_REPEAT;
        END_IF;
      END_REPEAT;
    END_IF;
    RETURN(TRUE);
  END_FUNCTION;

END_SCHEMA;
