(*
ISO TC184/SC4/WG12 N11356 - ISO/CD-TS 10303-1515 tessellated_boundary_representation - EXPRESS MIM
*)

SCHEMA Tessellated_boundary_representation_mim;
USE FROM Elemental_geometric_shape_mim;
USE FROM geometric_model_schema
         (tessellated_edge_curve,
          tessellated_face_surface,
          tessellated_brep_shape_representation,
          tessellated_vertex_point); --ISO 10303-42
END_SCHEMA;
