(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.17 2012/10/11 05:49:06 liutkuviene Exp
   ISO TC184/SC4/WG12 N8168 - ISO/TS 10303-1696 Layered interconnect module 3d design - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7563
*)


SCHEMA Layered_interconnect_module_3d_design_mim;
	USE FROM Physical_unit_3d_design_view_mim;	-- ISO/TS 10303-1727
	USE FROM Stratum_non_planar_shape_mim;	-- ISO/TS 10303-1748

END_SCHEMA;


