(*
   $Id: arm.exp,v 1.5 2008/09/13 12:25:15 liutkuviene Exp $
   ISO TC184/SC4/WG12 N11330 - ISO/TS 10303-1324 Non manifold surface - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5434
*)

SCHEMA Non_manifold_surface_arm;

USE FROM Elemental_geometric_shape_arm; -- ISO/CD-TS 10303-1004

USE FROM Topologically_bounded_surface_arm; --ISO/TS 10303-1511:2004

  ENTITY Non_manifold_shape_representation
    SUBTYPE OF (Geometric_model);
  END_ENTITY;

END_SCHEMA;
