(*
 Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.5 2012/10/11 05:49:13 liutkuviene Exp
 ISO TC184/SC4/WG12 N7832 - ISO/TS 10303-1525 Composite surface - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N7233
*)

SCHEMA Composite_surface_mim;

USE FROM Basic_geometry_mim;  -- ISO 10303-1652

USE FROM B_spline_geometry_mim; -- ISO 10303-1801 

USE FROM geometry_schema    -- ISO 10303-42
(rectangular_composite_surface,
 rectangular_trimmed_surface,
 surface_patch);

END_SCHEMA;
