(*
   $Id: mkmodule.js,v 1.46 2010/02/04 16:48:02 robbod Exp $
   ISO TC184/SC4/WG12 N10836 - ISO/TS 10303-1851 pmi_data_quality - EXPRESS MIM  
   *)

SCHEMA Pmi_data_quality_mim;

USE FROM Annotated_3d_model_data_quality_inspection_result_mim;  -- ISO/TS 10303-1849

USE FROM Associative_draughting_elements_mim;   --  ISO/TS 10303-1311

USE FROM Dimension_tolerance_mim;   --  ISO/TS 10303-1050

USE FROM Geometric_tolerance_mim;   --  ISO/TS 10303-1051

USE FROM Part_shape_mim;   --  ISO/TS 10303-1807

REFERENCE FROM shape_data_quality_criteria_schema  -- ISO 10303-59
    (value_limit_type);

REFERENCE FROM support_resource_schema 	--  ISO/TS 10303-1800
    (bag_to_set);

(*
4.2 MIM type definitions
*)

TYPE pmidq_inspected_element_select = SELECT BASED_ON inspected_element_select WITH
  (datum,
   datum_system,
   datum_target,
   dimensional_location, -- Geometric_dimension,
   dimensional_size, -- Geometric_dimension,
   geometric_tolerance,
   shape_aspect -- General_part_feature,
);
END_TYPE;

TYPE pmidq_inspected_element_type_name = ENUMERATION BASED_ON a3m_data_quality_inspected_element_type_name WITH
  (pmidqi_datum,
   pmidqi_datum_pair,
   pmidqi_datum_system,
   pmidqi_datum_target,
   pmidqi_dimensional_location, -- pmidqi_geometric_dimension,
   pmidqi_dimensional_size, -- pmidqi_geometric_dimension,
   pmidqi_geometric_tolerance,
   pmidqi_others,
   pmidqi_shape_aspect --pmidqi_general_part_feature,
   );
END_TYPE;

TYPE pmidq_measured_value_select = SELECT BASED_ON a3mir_data_quality_measured_value_select WITH
  (positive_length_measure,
   positive_plane_angle_measure);
END_TYPE;

TYPE pmidq_inspected_model_select = SELECT BASED_ON a3m_data_quality_inspected_model_select WITH 
   (draughting_model --Draughting_model
   );
END_TYPE;

TYPE pmidq_measured_data_type_name = ENUMERATION BASED_ON a3m_data_quality_measured_data_type_name WITH
  (pmidqm_boolean_value,
   pmidqm_positive_length_measure,
   pmidqm_positive_plane_angle_measure,
   pmidqm_others);
END_TYPE;

(*
4.2 MIM entity definitions
*)

ENTITY a3m_pmi_data_quality_criterion
  ABSTRACT SUPERTYPE OF ( ONEOF (a3m_erroneous_pmi_data, a3m_inapt_pmi_data))
  SUBTYPE OF (a3m_data_quality_criterion);
  SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name;
  SELF\a3m_data_quality_criterion.inspected_elements_types : LIST[1:?] OF pmidq_inspected_element_type_name;
DERIVE
  SELF\a3m_data_quality_criterion.accuracy_types : LIST[0:0] OF a3m_data_quality_accuracy_type_name := [];
  SELF\a3m_data_quality_criterion.location_of_extreme_value_types : LIST[0:0] OF a3m_data_quality_type_name_for_location_of_extreme_value := [];
WHERE
   WR1: SIZEOF(bag_to_set(USEDIN(SELF, 
     'ANNOTATED_3D_MODEL_DATA_QUALITY_CRITERIA_MIM.A3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.TARGET_TO_ASSOCIATE')
      )) = 0;
END_ENTITY;

ENTITY a3m_pmi_data_quality_inspection_result
  SUBTYPE OF (a3m_data_quality_inspection_result);
  SELF\a3m_data_quality_inspection_result.criterion_inspected : a3m_pmi_data_quality_criterion;
WHERE
   WR1: SIZEOF (QUERY(re <* bag_to_set(USEDIN(SELF,'ANNOTATED_3D_MODEL_DATA_QUALITY_INSPECTION_RESULT_MIM.DATA_QUALITY_INSPECTION_REPORT.INSPECTION_RESULT')) |NOT(pmidq_validate_element_types(re,SELF\A3m_data_quality_inspection_result.criterion_inspected)))) = 0;
   WR2: SIZEOF (QUERY(re <* bag_to_set(USEDIN(SELF,'ANNOTATED_3D_MODEL_DATA_QUALITY_INSPECTION_RESULT_MIM.DATA_QUALITY_INSPECTION_REPORT.INSPECTION_RESULT')) |NOT(pmidq_validate_measured_type(re,SELF\A3m_data_quality_inspection_result.criterion_inspected)))) = 0;
   WR3: SIZEOF(bag_to_set(USEDIN(SELF, 
     'ANNOTATED_3D_MODEL_DATA_QUALITY_CRITERIA_MIM.A3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.TARGET_TO_ASSOCIATE')
      )) = 0;
   WR4: SIZEOF (
   QUERY(re <* bag_to_set(USEDIN(SELF,'ANNOTATED_3D_MODEL_DATA_QUALITY_INSPECTION_RESULT_MIM.DATA_QUALITY_INSPECTION_REPORT.INSPECTION_RESULT'))
   |('PMI_DATA_QUALITY_MIM.DATA_QUALITY_INSPECTION_INSTANCE_REPORT' IN TYPEOF(re)) AND (SIZEOF(
     QUERY(ii <* re.inspected_instances|'PMI_DATA_QUALITY_MIM.A3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES' IN TYPEOF(ii))) <> 0)
      )) = 0;
END_ENTITY;

ENTITY a3m_erroneous_pmi_data
  ABSTRACT SUPERTYPE OF ( ONEOF ( 
    erroneous_pmi_representation, 
    erroneous_relation_of_pmi_and_feature))
  SUBTYPE OF (a3m_pmi_data_quality_criterion);
END_ENTITY;

ENTITY a3m_inapt_pmi_data
  ABSTRACT SUPERTYPE OF ( ONEOF ( 
    inapt_pmi_representation, 
    inapt_relation_of_pmi_and_feature))
  SUBTYPE OF (a3m_pmi_data_quality_criterion);
  SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
  DERIVE
    SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
       pmidqm_boolean_value;
END_ENTITY;

ENTITY erroneous_pmi_representation
  ABSTRACT SUPERTYPE OF ( ONEOF ( 
    incorrect_datum_reference_by_datum_target, 
    incorrect_unit_of_tolerance_value,
    duplicated_datum))
  SUBTYPE OF (a3m_erroneous_pmi_data);
  SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
  DERIVE
    SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
       pmidqm_boolean_value;
END_ENTITY;

ENTITY erroneous_relation_of_pmi_and_feature
  ABSTRACT SUPERTYPE OF ( ONEOF ( 
    no_general_part_feature_association, 
    incorrect_relation_of_geometric_tolerance_and_feature, 
    incorrect_relation_of_geometric_tolerance_and_datum_feature,
    inconsistent_feature_for_range_symbol,
    insufficiently_constrained_datum_system,
    incorrect_spatial_arrangement_of_datum_targets,
    incorrect_geometric_relation_of_datum_and_toleranced_feature,
    incorrect_relation_of_geometric_tolerance_modifier_to_feature,
    inconsistent_length_between_annotation_value_and_shape,
    inconsistent_angle_between_annotation_value_and_shape))
  SUBTYPE OF (a3m_erroneous_pmi_data);
END_ENTITY;

ENTITY inapt_pmi_representation
  ABSTRACT SUPERTYPE OF (  
    semantic_pmi_without_presentation)
  SUBTYPE OF (a3m_inapt_pmi_data);
END_ENTITY;

ENTITY inapt_relation_of_pmi_and_feature
  ABSTRACT SUPERTYPE OF ( ONEOF ( 
    geometric_tolerance_related_to_edge,
    general_part_feature_without_pmi))
  SUBTYPE OF (a3m_inapt_pmi_data);
END_ENTITY;

ENTITY duplicated_datum
  SUBTYPE OF (erroneous_pmi_representation);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum_pair];
END_ENTITY;


ENTITY incorrect_datum_reference_by_datum_target
  SUBTYPE OF (erroneous_pmi_representation);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum_target];
END_ENTITY;

ENTITY incorrect_unit_of_tolerance_value
  SUBTYPE OF (erroneous_pmi_representation);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[3:3] OF pmidq_inspected_element_type_name :=
    [pmidqi_dimensional_location, pmidqi_dimensional_size, pmidqi_geometric_tolerance];
END_ENTITY;

ENTITY no_general_part_feature_association
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[5:5] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum, pmidqi_datum_target, pmidqi_dimensional_location, pmidqi_dimensional_size, pmidqi_geometric_tolerance];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
END_ENTITY;

ENTITY incorrect_relation_of_geometric_tolerance_and_feature
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_geometric_tolerance];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
END_ENTITY;

ENTITY incorrect_relation_of_geometric_tolerance_and_datum_feature
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_geometric_tolerance];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
END_ENTITY;

ENTITY incorrect_relation_of_geometric_tolerance_modifier_to_feature
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_geometric_tolerance];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
END_ENTITY;

ENTITY insufficiently_constrained_datum_system
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
-- allowance : length_measure;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum_system];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
INVERSE
   allowance: pmidq_length_measure_for_insufficiently_constrained_datum_system FOR criterion_to_assign_the_value;
END_ENTITY;

ENTITY incorrect_spatial_arrangement_of_datum_targets
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
--allowance : length_measure;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
INVERSE
   allowance: pmidq_length_measure_for_incorrect_spatial_arrangement_of_datum_targets FOR criterion_to_assign_the_value;
END_ENTITY;

ENTITY incorrect_geometric_relation_of_datum_and_toleranced_feature
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
-- allowance : length_measure;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
INVERSE
   allowance: pmidq_length_measure_for_incorrect_geometric_relation_of_datum_and_toleranced_feature FOR criterion_to_assign_the_value;
END_ENTITY;

ENTITY inconsistent_length_between_annotation_value_and_shape
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_numerical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[2:2] OF pmidq_inspected_element_type_name :=
    [pmidqi_dimensional_location, pmidqi_dimensional_size];
SELF\a3m_data_quality_criterion.measured_data_type : 
    pmidq_measured_data_type_name :=
    pmidqm_positive_length_measure;
WHERE
   WR1: ('PMI_DATA_QUALITY_MIM.' + 'SHAPE_DATA_QUALITY_UPPER_VALUE_LIMIT' IN TYPEOF(SELF\a3m_data_quality_criterion.assessment_specification\shape_data_quality_assessment_by_numerical_test.threshold)) AND (pmidq_get_value_limit_type(SELF\a3m_data_quality_criterion.assessment_specification\shape_data_quality_assessment_by_numerical_test.threshold) = SELF.measured_data_type);
END_ENTITY;

ENTITY inconsistent_angle_between_annotation_value_and_shape
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_numerical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[2:2] OF pmidq_inspected_element_type_name :=
    [pmidqi_dimensional_location, pmidqi_dimensional_size];
SELF\a3m_data_quality_criterion.measured_data_type : 
    pmidq_measured_data_type_name :=
    pmidqm_positive_plane_angle_measure;
WHERE
   WR1: ('PMI_DATA_QUALITY_MIM.' + 'SHAPE_DATA_QUALITY_UPPER_VALUE_LIMIT' IN TYPEOF(SELF\a3m_data_quality_criterion.assessment_specification\shape_data_quality_assessment_by_numerical_test.threshold)) AND (pmidq_get_value_limit_type(SELF\a3m_data_quality_criterion.assessment_specification\shape_data_quality_assessment_by_numerical_test.threshold) = SELF.measured_data_type);
END_ENTITY;

ENTITY inconsistent_feature_for_range_symbol
  SUBTYPE OF (erroneous_relation_of_pmi_and_feature);
SELF\a3m_data_quality_criterion.assessment_specification : 
    shape_data_quality_assessment_by_logical_test;
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_geometric_tolerance];
SELF\a3m_data_quality_criterion.measured_data_type : pmidq_measured_data_type_name :=
     pmidqm_boolean_value;
END_ENTITY;


ENTITY semantic_pmi_without_presentation
  SUBTYPE OF (inapt_pmi_representation);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[5:5] OF pmidq_inspected_element_type_name :=
    [pmidqi_datum, pmidqi_datum_target, pmidqi_dimensional_location, pmidqi_dimensional_size, pmidqi_geometric_tolerance];
END_ENTITY;


ENTITY geometric_tolerance_related_to_edge
  SUBTYPE OF (inapt_relation_of_pmi_and_feature);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_geometric_tolerance];
END_ENTITY;

ENTITY general_part_feature_without_pmi
  SUBTYPE OF (inapt_relation_of_pmi_and_feature);
DERIVE
SELF\a3m_data_quality_criterion.inspected_elements_types :
    LIST[1:1] OF pmidq_inspected_element_type_name :=
    [pmidqi_shape_aspect];
END_ENTITY;

  ENTITY pmidq_length_measure_for_insufficiently_constrained_datum_system
    SUBTYPE OF(a3m_data_quality_criterion_specific_applied_value);
      SELF\a3m_data_quality_criterion_specific_applied_value.criterion_to_assign_the_value : insufficiently_constrained_datum_system;
      SELF\a3m_data_quality_criterion_specific_applied_value.applied_value : length_measure;
  END_ENTITY;

  ENTITY pmidq_length_measure_for_incorrect_spatial_arrangement_of_datum_targets
    SUBTYPE OF(a3m_data_quality_criterion_specific_applied_value);
      SELF\a3m_data_quality_criterion_specific_applied_value.criterion_to_assign_the_value : incorrect_spatial_arrangement_of_datum_targets;
      SELF\a3m_data_quality_criterion_specific_applied_value.applied_value : length_measure;
  END_ENTITY;

  ENTITY pmidq_length_measure_for_incorrect_geometric_relation_of_datum_and_toleranced_feature
    SUBTYPE OF(a3m_data_quality_criterion_specific_applied_value);
      SELF\a3m_data_quality_criterion_specific_applied_value.criterion_to_assign_the_value : incorrect_geometric_relation_of_datum_and_toleranced_feature;
      SELF\a3m_data_quality_criterion_specific_applied_value.applied_value : length_measure;
  END_ENTITY;



  FUNCTION pmidq_get_inspected_element_type_name
    (ei:SET [1:?] OF inspected_element_select):pmidq_inspected_element_type_name;
     LOCAL
      type_out : SET OF STRING;
    END_LOCAL;
    IF(SIZEOF(ei) > 2) THEN
      RETURN(pmidqi_others);
    END_IF;
    IF(SIZEOF(ei) = 2) THEN
      IF(TYPEOF(ei[1]) = TYPEOF(ei[2])) THEN
        type_out := TYPEOF(ei[1]);
        IF('PMI_DATA_QUALITY_MIM.DATUM' IN type_out) THEN
           RETURN(pmidqi_datum_pair);
        END_IF;
      END_IF;
    ELSE IF(SIZEOF(ei) = 1) THEN
      type_out := TYPEOF(ei[1]);
      IF('PMI_DATA_QUALITY_MIM.DATUM' IN type_out) THEN
         RETURN(pmidqi_datum);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.DATUM_SYSTEM' IN type_out) THEN
         RETURN(pmidqi_datum_system);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.DATUM_TARGET' IN type_out) THEN
         RETURN(pmidqi_datum_target);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.DIMENSIONAL_LOCATION' IN type_out) THEN
         RETURN(pmidqi_dimensional_location);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.DIMENSIONAL_SIZE' IN type_out) THEN
         RETURN(pmidqi_dimensional_size);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.GEOMETRIC_TOLERANCE' IN type_out) THEN
         RETURN(pmidqi_geometric_tolerance);
      END_IF;
      IF('PMI_DATA_QUALITY_MIM.SHAPE_ASPECT' IN type_out) THEN
         RETURN(pmidqi_shape_aspect);
      END_IF;
    END_IF;
    END_IF;  
    RETURN(pmidqi_others);
   END_FUNCTION;

  FUNCTION pmidq_get_measured_type_name
    (ei:a3m_data_quality_measured_value_select):pmidq_measured_data_type_name;
    LOCAL
      type_out : SET OF STRING;
    END_LOCAL;
    type_out := TYPEOF(ei);
    IF('PMI_DATA_QUALITY_MIM.BOOLEAN_VALUE' IN type_out) THEN
       RETURN(pmidqm_boolean_value);
    END_IF;
    IF('PMI_DATA_QUALITY_MIM.POSITIVE_LENGTH_MEASURE' IN type_out) THEN
       RETURN(pmidqm_positive_length_measure);
    END_IF;
    IF('PMI_DATA_QUALITY_MIM.POSITIVE_PLANE_ANGLE_MEASURE' IN type_out) THEN
       RETURN(pmidqm_positive_plane_angle_measure);
    END_IF;
    RETURN(pmidqm_others);
   END_FUNCTION;


 FUNCTION  pmidq_get_value_limit_type(sdqvlts : shape_data_quality_value_limit_type_select) : pmidq_measured_data_type_name;
	LOCAL
      type_out : SET OF STRING :=[];
    END_LOCAL;
    type_out := value_limit_type(sdqvlts);
    IF('PMI_DATA_QUALITY_MIM.POSITIVE_LENGTH_MEASURE' IN type_out) THEN
       RETURN(pmidqm_positive_length_measure);
    END_IF;
    IF('PMI_DATA_QUALITY_MIM.POSITIVE_PLANE_ANGLE_MEASURE' IN type_out) THEN
       RETURN(pmidqm_positive_plane_angle_measure);
    END_IF;
    RETURN(pmidqm_others);
 END_FUNCTION;

 FUNCTION  pmidq_validate_element_types(ir:data_quality_inspection_report;cr:a3m_pmi_data_quality_criterion):LOGICAL;
    LOCAL
      aqiiri : a3m_data_quality_inspection_instance_report_item;
      dqiir : data_quality_inspection_instance_report;
      pietn : LIST [1:?] OF pmidq_inspected_element_type_name;
    END_LOCAL;
    pietn := cr.inspected_elements_types;
    -- Data_quality_inspection_instance_report
    IF('PMI_DATA_QUALITY_MIM.DATA_QUALITY_INSPECTION_INSTANCE_REPORT' IN TYPEOF(ir)) THEN
      dqiir := ir;
      REPEAT i := 1 TO SIZEOF(dqiir.inspected_instances);
    --   > A3m_data_quality_inspection_instance_report_item.representative_measured_value
        IF('PMI_DATA_QUALITY_MIM.A3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM'
           IN TYPEOF(dqiir.inspected_instances[i])) THEN
           aqiiri := dqiir.inspected_instances[i];
           IF(NOT(pmidq_get_inspected_element_type_name(aqiiri.inspected_elements) IN pietn)) THEN
             RETURN(FALSE);
           END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
  RETURN(TRUE);
 END_FUNCTION;

 
 FUNCTION  pmidq_validate_measured_type(ir:data_quality_inspection_report;cr:a3m_pmi_data_quality_criterion):LOGICAL;
    LOCAL
      aqicri : a3m_data_quality_inspection_criterion_report_item;
      aqiiri : a3m_data_quality_inspection_instance_report_item;
      aqirie : a3m_instance_report_item_with_extreme_instances;
      dqicr : data_quality_inspection_criterion_report;
      dqiir : data_quality_inspection_instance_report;
      pmdtn : pmidq_measured_data_type_name;
    END_LOCAL;
    pmdtn := cr.measured_data_type;
    -- Data_quality_inspection_criterion_report
    IF('PMI_DATA_QUALITY_MIM.DATA_QUALITY_INSPECTION_CRITERION_REPORT' IN TYPEOF(ir)) THEN
      dqicr := ir;
      REPEAT i := 1 TO SIZEOF(dqicr.statistical_values);
    -- A3m_data_quality_inspection_criterion_report_item.representative_measured_value
        IF('PMI_DATA_QUALITY_MIM.A3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM'
           IN TYPEOF(dqicr.statistical_values[i])) THEN
           aqicri := dqicr.statistical_values[i];
           IF(pmidq_get_measured_type_name(aqicri.representative_measured_value) <> pmdtn) THEN
             RETURN(FALSE);
           END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
    -- Data_quality_inspection_instance_report
    IF('PMI_DATA_QUALITY_MIM.DATA_QUALITY_INSPECTION_INSTANCE_REPORT' IN TYPEOF(ir)) THEN
      dqiir := ir;
      REPEAT i := 1 TO SIZEOF(dqiir.inspected_instances);
    --   > A3m_data_quality_inspection_instance_report_item.representative_measured_value
        IF('PMI_DATA_QUALITY_MIM.A3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM'
           IN TYPEOF(dqiir.inspected_instances[i])) THEN
           aqiiri := dqiir.inspected_instances[i];
           IF(pmidq_get_measured_type_name(aqiiri.representative_measured_value) <> pmdtn) THEN
             RETURN(FALSE);
           END_IF;
        END_IF;
    --   >     A3m_instance_report_item_with_extreme_instances
        IF('PMI_DATA_QUALITY_MIM.A3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES'
           IN TYPEOF(dqiir.inspected_instances[i])) THEN
           aqirie := dqiir.inspected_instances[i];
           REPEAT j := 1 TO SIZEOF(aqirie.extreme_instances);
             IF(pmidq_get_measured_type_name(aqirie.extreme_instances[j].measured_value) <> pmdtn) THEN
               RETURN(FALSE);
             END_IF;
           END_REPEAT;
        END_IF;
      END_REPEAT;
    END_IF;
  RETURN(TRUE);
 END_FUNCTION;
 
END_SCHEMA;
