(*
   ISO TC184/SC4/WG12 N11456 - ISO/TS 10303-442 AP242 managed model based 3d engineering - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N11274
*)

SCHEMA Ap242_managed_model_based_3d_engineering_mim;

   USE FROM geometry_schema;
   USE FROM Activity_as_realized_mim; --ISO/TS 10303-1259
   USE FROM Additive_manufacturing_part_and_build_information_mim; --ISO/TS 10303-1835
   USE FROM Analysis_assignment_mim; --ISO/TS 10303-1474
   USE FROM Analysis_identification_mim;    -- ISO/TS 10303-1476
   USE FROM Analysis_representation_mim;    -- ISO/TS 10303-1785
   USE FROM Annotated_3d_model_equivalence_assembly_mim;    -- ISO/TS 10303-1841
   USE FROM application_context_schema   -- ISO 10303-41
            (application_context,
            application_protocol_definition,
            product_context,
            product_definition_context);
   USE FROM Assembly_constraints_mim;   -- ISO/TS 10303-1794
   USE FROM Attachment_slot_mim;    -- ISO/TS 10303-1250
   USE FROM Change_management_mim; -- ISO/TS 10303-1661
   USE FROM Characterized_representation_mim;   -- ISO/TS 10303-1805
   USE FROM Chemical_substance_mim; -- ISO/TS 10303-1655
   USE FROM Collection_identification_and_version_mim;    -- ISO/TS 10303-1396
   USE FROM Composite_material_aspects_mim; -- ISO/TS 10303-1768
   USE FROM Conditional_effectivity_mim; -- ISO/TS 10303-1397
   USE FROM Constructive_solid_geometry_2d_mim; -- ISO/TS 10303-1731
   USE FROM Curve_swept_solid_mim; -- ISO/TS 10303-1659
   USE FROM Default_tolerance_mim; -- ISO/TS 10303-1052
   USE FROM Description_assignment_mim; -- ISO/TS 10303-1473
   USE FROM Design_product_data_management_mim; -- ISO/TS 10303-1628
   USE FROM Dimension_and_tolerance_callouts_mim; -- ISO/TS 10303-1362
   USE FROM Dimension_tolerance_mim; -- ISO/TS 10303-1050
   USE FROM Drawing_definition_mim;  -- ISO/TS 10303-1309
   USE FROM Edge_shape_feature_mim; -- ISO/TS 10303-1673
   USE FROM Envelope_mim;    -- ISO/TS 10303-1265
   USE FROM Event_assignment_mim;    -- ISO/TS 10303-1364
   USE FROM Experience_mim;    -- ISO/TS 10303-1243
   USE FROM External_currency_mim; -- ISO/TS 10303-1777
   USE FROM External_representation_item_mim; -- ISO/TS 10303-1779
   USE FROM Externally_conditioned_data_quality_inspection_result_mim; -- ISO/TS 10303-1822
   USE FROM Form_feature_in_panel_mim;    -- ISO/TS 10303-1806
   USE FROM Foundation_state_definition_mim;    -- ISO/TS 10303-1469
   USE FROM Geometric_constraints_mim; -- ISO/TS 10303-1789
   USE FROM Geometric_tolerance_mim; -- ISO/TS 10303-1051
   USE FROM Geometric_validation_property_representation_mim; -- ISO/TS 10303-1039
   USE FROM Identification_relationship_mim; -- ISO/TS 10303-1398
   USE FROM Inertia_characteristics_mim; -- ISO/TS 10303-1350
   USE FROM Interface_mim;    -- ISO/TS 10303-1251
   USE FROM Interface_component_mim;    -- ISO/TS 10303-1691
   USE FROM Interface_lifecycle_mim;    -- ISO/TS 10303-1294
   USE FROM Kinematic_analysis_control_and_result_mim;   -- ISO/TS 10303-1817
   USE FROM Limited_length_or_area_indicator_assignment_mim;   -- ISO/TS 10303-1854
   USE FROM Location_mim;    --  ISO/TS 10303-1276
   USE FROM Location_assignment_mim;   -- ISO/TS 10303-1277
   USE FROM Machining_features_mim;   -- ISO/TS 10303-1814
   USE FROM Mating_structure_mim;   -- ISO/TS 10303-1815
   USE FROM Mechanical_design_features_and_requirements_mim;  --ISO/TS 10303-1846
   USE FROM Mechanical_design_presentation_representation_with_draughting_mim; -- ISO/TS 10303-1315
   USE FROM Message_mim;    -- ISO/TS 10303-1270
   USE FROM Model_based_3d_geometrical_dimensioning_and_tolerancing_representation_mim;   -- ISO/TS 10303-1816
   USE FROM Modified_swept_solid_mim; -- ISO/TS 10303-1322
   USE FROM Numerical_interface_mim; -- ISO/TS 10303-1344
   USE FROM Observation_mim;-- ISO/TS 10303-1258
   USE FROM Organization_type_mim; -- ISO/TS 10303-1240
   USE FROM Part_and_zone_laminate_tables_mim;  -- ISO/TS 10303-1770
   USE FROM Position_in_organization_mim;	-- ISO/TS 10303-1242
   USE FROM Physical_breakdown_mim; -- ISO/TS 10303-1215
   USE FROM Picture_representation_mim;  -- ISO/TS 10303-1308
   USE FROM Planned_characteristic_mim; -- ISO/TS 10303-1733
   USE FROM Ply_orientation_specification_mim;  -- ISO/TS 10303-1772
   USE FROM Pmi_data_quality_mim;  -- ISO/TS 10303-1851
   USE FROM Point_direction_model_mim;  -- -- ISO/TS 10303-1820
   USE FROM Process_plan_mim;   -- ISO/TS 10303-1803
   USE FROM Product_and_manufacturing_annotation_presentation_mim;   -- ISO/TS 10303-1812
   USE FROM Product_as_individual_assembly_and_test_mim;   -- ISO/TS 10303-1804
   USE FROM product_concept_schema(product_concept_relationship);   -- ISO 10303-44
   USE FROM product_definition_schema(  -- ISO 10303-41
            alternative_solution_relationship,
            product_category_relationship,
            product_definition_context_role);
   USE FROM product_property_representation_schema(   -- ISO 10303-41
            item_identified_representation_usage_definition);
   USE FROM Product_group_mim;    -- ISO/TS 10303-1278
   USE FROM Required_resource_mim;    -- ISO/TS 10303-1267
   USE FROM Requirement_assignment_mim;    -- ISO/TS 10303-1233
   USE FROM Requirement_management_mim;    -- ISO/TS 10303-1348
   USE FROM Resource_as_realized_mim;    -- ISO/TS 10303-1269
   USE FROM Risk_definition_mim;    -- ISO/TS 10303-1786
   USE FROM Same_as_external_item_mim;    -- ISO/TS 10303-1402
   USE FROM Scan_data_3d_shape_mim; --ISO/TS 10303-1831
   USE FROM Shape_data_quality_inspection_result_mim; -- ISO/TS 10303-1524
   USE FROM Shape_feature_mim;    -- ISO/TS 10303-1764
   USE FROM Sketch_mim; -- ISO/TS 10303-1792
   USE FROM Solid_with_local_modification_mim; -- ISO/TS 10303-1319
   USE FROM State_characterized_mim;    -- ISO/TS 10303-1271
   USE FROM State_definition_mim;    -- ISO/TS 10303-1255
   USE FROM State_observed_mim;  -- ISO/TS 10303-1256
   USE FROM Surface_conditions_mim; -- ISO/TS 10303-1110
   USE FROM Surface_visual_texture_mim; -- ISO/TS 10303-1834
   USE FROM System_breakdown_mim; -- ISO/TS 10303-1214
   USE FROM Tessellated_geometry_mim;  -- ISO/TS 10303-1819
   USE FROM Task_element_mim;  -- ISO/TS 10303-1480
   USE FROM Task_specification_mim;  -- ISO/TS 10303-1262
   USE FROM Text_representation_mim;	-- ISO/TS 10303-1750
   USE FROM Thickened_face_solid_mim; -- ISO/TS 10303-1320
   USE FROM Triangulated_shape_data_quality_mim; -- ISO/TS 10303-1850
   USE FROM Type_of_person_mim;  -- ISO/TS 10303-1245
   USE FROM Verification_and_validation_mim;    -- ISO/TS 10303-1488
   USE FROM Vertex_colours_for_tessellated_geometry_mim;  -- ISO/TS 10303-1836
   USE FROM Wireframe_2d_mim; -- ISO/TS 10303-1347
   USE FROM Wiring_harness_assembly_design_mim;   -- ISO/TS 10303-1828
   USE FROM Zonal_breakdown_mim; -- ISO/TS 10303-1217
   USE FROM state_type_schema;  -- ISO 10303-56
   USE FROM management_resources_schema   -- ISO 10303-41
   		(assignment_object_relationship,
         assignment_object_select);
   USE FROM material_property_definition_schema --ISO 10303-45
				(generic_property_relationship);


   REFERENCE FROM product_property_definition_schema(   -- ISO 10303-41
           acyclic_shape_aspect_relationship);
   REFERENCE FROM representation_schema(founded_item);   -- ISO 10303-43
   REFERENCE FROM support_resource_schema   -- ISO 10303-41
                  (bag_to_set,
                  type_check_function);



CONSTANT
    ap242_shape_representation_reference_types : SET OF STRING :=
       ['GEOMETRIC_MODEL_SCHEMA.ADVANCED_BREP_SHAPE_REPRESENTATION',
        'COMPOSITE_CONSTITUENT_SHAPE_MIM.BEVELED_SHEET_REPRESENTATION',
        'COMPOSITE_CONSTITUENT_SHAPE_MIM.COMPOSITE_SHEET_REPRESENTATION',
        'COMPOUND_SHAPE_REPRESENTATION_MIM.COMPOUND_SHAPE_REPRESENTATION',
        'CONSTRUCTIVE_SOLID_GEOMETRY_2D_MIM.CSG_2D_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.CSG_SHAPE_REPRESENTATION',
        'AIC_CURVE_SWEPT_SOLID.CURVE_SWEPT_SOLID_SHAPE_REPRESENTATION',
        'MACHINING_FEATURE_SCHEMA.DIRECTION_SHAPE_REPRESENTATION',
        'AIC_EDGE_BASED_WIREFRAME.EDGE_BASED_WIREFRAME_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.ELEMENTARY_BREP_SHAPE_REPRESENTATION',
        'MACHINING_FEATURE_SCHEMA.FACE_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.FACETED_BREP_SHAPE_REPRESENTATION',
        'AIC_GEOMETRICALLY_BOUNDED_2D_WIREFRAME.GEOMETRICALLY_BOUNDED_2D_WIREFRAME_REPRESENTATION',
        'AIC_GEOMETRICALLY_BOUNDED_SURFACE.GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION',
        'AIC_GEOMETRICALLY_BOUNDED_WIREFRAME.GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION',
        'MACHINING_FEATURE_SCHEMA.LOCATION_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.MANIFOLD_SUBSURFACE_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.MANIFOLD_SURFACE_SHAPE_REPRESENTATION',
        'SKETCH_SCHEMA.NEUTRAL_SKETCH_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.NON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION',
        'MACHINING_FEATURE_SCHEMA.PATH_SHAPE_REPRESENTATION',
        'MACHINING_FEATURE_SCHEMA.PLANAR_SHAPE_REPRESENTATION',
        'POINT_DIRECTION_MODEL_MIM.POINT_PLACEMENT_SHAPE_REPRESENTATION',
        'PROCEDURAL_SHAPE_MODEL_SCHEMA.PROCEDURAL_SHAPE_REPRESENTATION',
        'ASSEMBLY_FEATURE_RELATIONSHIP_SCHEMA.REPRESENTATIVE_SHAPE_REPRESENTATION',
        'SCAN_DATA_3D_SHAPE_MODEL_SCHEMA.SCAN_DATA_SHAPE_REPRESENTATION',
        'SHAPE_DIMENSION_SCHEMA.SHAPE_DIMENSION_REPRESENTATION',
        'SHAPE_ASPECT_DEFINITION_SCHEMA.SHAPE_REPRESENTATION_WITH_PARAMETERS',
        'AIC_SHELL_BASED_WIREFRAME.SHELL_BASED_WIREFRAME_SHAPE_REPRESENTATION',
        'GEOMETRIC_MODEL_SCHEMA.TESSELLATED_SHAPE_REPRESENTATION'];
    deprecated_interfaced_data_types : SET OF STRING :=
      ['document_with_class',
       'ordinal_date',
       'product_definition_formation_with_specified_source',
       'week_of_year_and_day_date'];
    deprecated_constructed_data_types : SET OF STRING :=
      ['angle_direction_reference_select',
       'approved_item',
       'certified_item',
       'change_request_item',
       'contracted_item',
       'cc_classified_item',
       'date_time_item',
       'cc_person_organization_item',
       'cc_specified_item',
       'start_request_item',
       'work_item'];
    deprecated_entity_data_types : SET OF STRING :=
      ['angle_direction_reference',
       'cc_design_approval',
       'cc_design_certification',
       'cc_design_contract',
       'cc_design_date_and_time_assignment',
       'cc_design_person_and_organization_assignment',
       'cc_design_security_classification',
       'cc_design_specification_reference',
       'change',
       'change_request',
       'design_context',
       'design_make_from_relationship',
       'mechanical_context',
       'min_and_major_ply_orientation_basis',
       'product_category_relationship',
       'start_request',
       'start_work',
       'supplied_part_relationship'];
  END_CONSTANT;

  TYPE ap242_action_method_items = SELECT BASED_ON action_method_items WITH (
     action_method,
     action_property_representation,
     applied_action_assignment,
     applied_action_method_assignment,
     applied_action_request_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_contract_assignment,
     applied_document_reference,
     applied_document_usage_constraint_assignment,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_ineffectivity_assignment,
     applied_organization_assignment,
     applied_organizational_project_assignment,
     applied_person_and_organization_assignment,
     applied_security_classification_assignment,
     applied_time_interval_assignment,
     applied_usage_right,
     breakdown_of,
     configuration_design,
     contract,
     contract_assignment,
     date_and_time_assignment,
     date_assignment,
     directed_action_assignment,
     document_file,
     envelope,
     executed_action,
     frozen_assignment,
     general_property_relationship,
     material_designation_characterization,
     organization,
     organizational_address,
     organizational_project,
     person,
     person_and_organization,
     person_and_organization_address,
     product,
     product_class,
     product_concept_feature_association,
     product_concept_feature_category_usage,
     product_definition,
     product_definition_formation,
     product_definition_formation_relationship,
     product_definition_relationship,
     product_identification,
     property_definition,
     property_definition_representation,
     representation_relationship,
     requirement_assignment,
     requirement_for_action_resource,
     requirement_view_definition_relationship,
     structured_message,
     versioned_action_request
     );
  END_TYPE;

-- NOTE: condition_action_method_items is an extension of action_method_items
  TYPE ap242_condition_action_method_items = SELECT BASED_ON condition_action_method_items WITH 
   (action_method,
    action_method_relationship,
    action_property,
    action_property_representation,
    action_request_solution,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_certification_assignment,
    applied_contract_assignment,
    applied_description_text_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_ineffectivity_assignment,
    applied_organization_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    approval,
    breakdown_of,
    condition,
    date_and_time,
    date_and_time_assignment,
    date_assignment,
    directed_action_assignment,
    effectivity,
    evidence,
    executed_action,
    externally_defined_general_property,
    frozen_assignment,
    general_property,
    general_property_relationship,
    hierarchical_interface_connection,
    interface_connection,
    interface_connector_occurrence,
    interface_definition_connection,
    material_designation_characterization,
    measure_representation_item,
    organization,
    organizational_address,
    package_product_concept_feature,
    person_and_organization_address,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category_usage,
    product_definition_relationship,
    product_design_version_to_individual,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_identification,
    property_definition_representation,
    representation_item,
    representation_relationship,
    requirement_assignment,
    requirement_for_action_resource,
    state_observed,
    state_type,
    validation,
    value_representation_item,
    verification,
    versioned_action_request);
  END_TYPE;

  TYPE ap242_in_zone_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON in_zone_groupable_item WITH
   (action_method,
    applied_action_method_assignment,
    interface_connection,
   	interface_connector_occurrence,
    interface_definition_connection);
  END_TYPE;

  TYPE ap242_location_item = SELECT BASED_ON location_item WITH
   (assembly_component_usage,
    document_file,
    interface_connection,
    interface_connector_occurrence,
    interface_definition_connection,
    organization,
    organization_type,
    organizational_project,
    person,
    person_and_organization,
    product,
    product_definition,
    product_definition_formation,
    product_definition_relationship,
    product_group);
  END_TYPE;

  TYPE ap242_description_item = SELECT BASED_ON description_item WITH
   (action,
    action_directive,
    action_directive_relationship,
    action_method,
    action_method_relationship,
    action_property,
    action_property_representation,
    action_relationship,
    address,
    alternate_product_relationship,
    alternative_solution_relationship,
    analysis_representation_context,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_certification_assignment,
    applied_classification_assignment,
    applied_classification_assignment_relationship,
    applied_contract_assignment,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_external_identification_assignment_relationship,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_location_assignment,
    applied_location_representation_assignment,
    applied_organization_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_state_observed_assignment,
    applied_state_type_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    approval,
    approval_relationship,
    ascribable_state,
    ascribable_state_relationship,
    assembly_component_usage_substitute,
    assignment_object_relationship,
    breakdown_element_group_assignment,
    certification,
    change_element_sequence,
    change_group,
    configuration_design,
    configuration_effectivity,
    configuration_item,
    configuration_item_relationship,
    contract,
    contract_relationship,
    data_environment,
    date_and_time_assignment,
    date_assignment,
    directed_action_assignment,
    document_file,
    document_relationship,
    effectivity,
    effectivity_relationship,
    envelope,
    envelope_relationship,
    evaluated_characteristic,
    event_occurrence,
    event_occurrence_relationship,
    exclusive_product_concept_feature_category,
    general_property,
    general_property_relationship,
   	generic_property_relationship,
    geometric_item_specific_usage,
    global_uncertainty_assigned_context,
    global_unit_assigned_context,
    group,
    group_relationship,
    location,
    location_relationship,
    material_designation_characterization,
    measure_qualification,
    measure_with_unit,
    message_relationship,
    organization,
    organization_relationship,
    organization_type,
    organizational_address,
    organizational_project,
    organizational_project_relationship,
    package_product_concept_feature,
    person,
    person_and_organization,
    person_and_organization_address,
    process_operation,
    process_plan,
    process_product_association,
    product,
    product_concept,
    product_concept_context,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_concept_relationship,
    product_definition,
    product_definition_context,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_group_assignment,
    product_definition_relationship,
    product_definition_usage,
    product_definition_usage_relationship,
    product_group_membership,
    product_group_relationship,
    product_process_plan,
    product_relationship,
    property_definition,
    property_definition_representation,
    representation,
    representation_context,
    representation_item,
    representation_relationship,
    requirement_for_action_resource,
    retention,
    satisfies_requirement,
    security_classification,
    shape_aspect,
    shape_aspect_relationship,
    shape_feature_definition,
    shape_feature_definition_relationship,
    state_definition_to_state_assignment_relationship,
    state_observed,
    state_observed_assignment,
    state_observed_relationship,
    state_observed_role,
    state_type,
    state_type_assignment,
    state_type_relationship,
    state_type_role,
    structured_message,
    time_interval,
    time_interval_relationship,
    uncertainty_measure_with_unit,
    uncertainty_qualifier,
    usage_association,
    verification_relationship,
    versioned_action_request,
    versioned_action_request_relationship
    );
END_TYPE;

  TYPE property_variable_rep_select_242 = SELECT BASED_ON property_variable_rep_select WITH
   (dimensional_size,
    representation);
  END_TYPE;

  TYPE item_identified_representation_usage_definition_242 = SELECT BASED_ON item_identified_representation_usage_definition WITH
   (applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_certification_assignment,
    applied_classification_assignment,
    applied_contract_assignment,
    applied_date_and_time_assignment,
    applied_date_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_group_assignment,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_name_assignment,
    applied_organization_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    product_definition_relationship,
    property_definition);
  END_TYPE;

  TYPE draughting_model_item_definition_242 = SELECT BASED_ON draughting_model_item_definition WITH
   (applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_certification_assignment,
    applied_classification_assignment,
    applied_contract_assignment,
    applied_date_and_time_assignment,
    applied_date_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_group_assignment,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_name_assignment,
    applied_organization_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    product_definition_relationship,
    property_definition);
  END_TYPE;
  
  TYPE ap242_product_definition_or_breakdown_element_usage = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON product_definition_or_breakdown_element_usage WITH
     (product,
      product_definition_formation);
  END_TYPE;

  TYPE ap242_change_management_object = SELECT BASED_ON change_management_object WITH
    (action,
     action_items,
     action_method,
     action_method_relationship,
     action_property,
     action_property_representation,
     action_relationship,
     applied_action_assignment,
     applied_action_method_assignment,
     applied_action_request_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_contract_assignment,
     applied_document_reference,
     applied_document_usage_constraint_assignment,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_ineffectivity_assignment,
     applied_organization_assignment,
     applied_organizational_project_assignment,
     applied_person_and_organization_assignment,
     applied_security_classification_assignment,
     applied_time_interval_assignment,
     applied_usage_right,
     assembly_component_usage_substitute,
     assembly_component_usage,
     assignment_object_relationship,
     breakdown_of,
     class,
     condition,
     conditional_effectivity,
     configuration_effectivity,
     contract,
     date_and_time_assignment,
     date_assignment,
     directed_action_assignment,
     document_file,
     effectivity,
     event_occurrence,
     exclusive_product_concept_feature_category,
     frozen_assignment,
     general_property_relationship,
     identification_item,
     inclusion_product_concept_feature,
     material_designation_characterization,
     material_designation,
     measure_representation_item,
     organization,
     organizational_address,
     organizational_project_relationship,
     organizational_project,
     package_product_concept_feature,
     person_and_organization_address,
     person_and_organization,
     person,
     process_operation,
     process_plan,
     product_class,
     product_concept_feature_association,
     product_concept_feature_category_usage,
     product_concept_feature_category,
     product_concept_feature,
     product_definition_formation_relationship,
     product_definition_formation,
     product_definition_group_assignment,
     product_definition_occurrence_reference,
     product_definition_occurrence,
     product_definition_relationship,
     product_definition_substitute,
     product_definition,
     product_identification,
     product_process_plan,
     product,
     project_item,
     property_definition_representation,
     property_definition,
     representation_relationship,
     requirement_assignment,
     requirement_for_action_resource,
     requirement_view_definition_relationship,
     value_representation_item
     );
  END_TYPE;

  TYPE ap242_change_relationship_select = SELECT BASED_ON change_relationship_select WITH
    (action_relationship,
     alternative_solution_relationship,
     product_definition_relationship,
     shape_aspect_relationship
     );
  END_TYPE;
  

  TYPE action_request_item_242 = SELECT BASED_ON action_request_item WITH
   (action,
    action_method,
    action_property,
    action_relationship,
    alternate_product_relationship,
    assembly_component_usage_substitute,
    configuration_design,
    configuration_effectivity,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    document_file,
    draughting_model,
    drawing_revision,
    executed_action,
    general_property,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organization,
    organizational_project,
    person,
    person_and_organization,
    presentation_area,
    product,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition_formation_relationship,
    product_definition_relationship,
    product_definition_substitute,
    product_identification,
    resource_property,
    shape_aspect,
    shape_representation);
  END_TYPE;
  
  TYPE ap242_analysed_item = SELECT BASED_ON analysed_item WITH
   (action_property_representation,
    alternate_product_relationship,
    ascribable_state,
    assembly_component_usage_substitute,
    evidence,
    interface_connection,
    interface_connector_occurrence,
    organization,
    organization_relationship,
    organizational_project_relationship,
    product,
    product_concept,
    product_definition,
    product_definition_context,
    product_definition_formation_relationship,
    product_definition_relationship,
    product_group_relationship,
    product_relationship,
    property_definition,
    property_definition_representation,
    requirement_assignment,
    state_observed,
    state_observed_assignment,
    state_observed_role,
    state_type,
    validation,
    verification,
    verification_relationship);
END_TYPE;

TYPE ap242_assignment_object_select = SELECT BASED_ON assignment_object_select WITH (
    action_property,
    action_property_representation,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_document_reference,
	applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_ineffectivity_assignment,
	applied_organization_assignment,
	applied_organizational_project_assignment,
	applied_person_and_organization_assignment,
	applied_security_classification_assignment,
	applied_time_interval_assignment,
	applied_usage_right,
	breakdown_of,
	date_and_time_assignment,
	date_assignment,
	directed_action_assignment,
	frozen_assignment,
	material_designation_characterization,
	organizational_address,
	person_and_organization_address,
	product_concept_feature_association,
	product_concept_feature_category_usage,
	property_definition,
	property_definition_representation,
	requirement_assignment,
	requirement_for_action_resource);
END_TYPE;

  TYPE approval_item_242 = SELECT BASED_ON approval_item WITH
   (action_method,
    action_method_relationship,
    action_property,
    action_property_representation,
    action_request_solution,
    alternate_product_relationship,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_external_identification_assignment,
    applied_ineffectivity_assignment,
    applied_time_interval_assignment,
    assembly_component_usage_substitute,
    breakdown_of,
    certification,
    class,
    class_system,
    configuration_design,
    configured_effectivity_assignment,
    contract,
    date,
    datum,
    datum_system,
    dimensional_location,
    dimensional_size,
    directed_action,
    directed_action_assignment,
    document,
    document_file,
    draughting_model,
    drawing_revision,
    evaluated_characteristic_of_product_as_individual_test_result,
    evidence,
    exclusive_product_concept_feature_category,
    executed_action,
    externally_defined_general_property,
    general_property,
    geometric_tolerance,
    identification_assignment_relationship,
    in_zone,
    inclusion_product_concept_feature,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_definition,
    interface_connector_design,
    interface_connector_design_to_planned,
    interface_connector_design_to_realized,
    interface_connector_occurrence,
    interface_connector_planned_to_realized,
    interface_connector_version,
    interface_definition_for,
    interface_specification_definition,
    interface_specification_version,
    material_designation,
    material_designation_characterization,
    measure_representation_item,
    mechanical_design_geometric_presentation_representation,
    organization,
    package_product_concept_feature,
    presentation_area,
    process_plan,
    product,
    product_class,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_context,
    product_definition_formation,
    product_definition_group_assignment,
    product_definition_relationship,
    product_definition_substitute,
    product_definition_usage,
    product_process_plan,
    product_relationship,
    property_definition_representation,
    representation,
    representation_item,
    representation_relationship,
    requirement_for_action_resource,
    resource_property,
    shape_aspect_relationship,
    shape_representation,
    validation,
    value_representation_item,
    verification);
  END_TYPE;

  TYPE approved_item = SELECT
    (certification,
    change,
    change_request,
    configuration_effectivity,
    configuration_item,
    contract,
    product,
    security_classification,
    start_request,
    start_work);
  END_TYPE;

  TYPE ap242_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
   (action_property,
    context_dependent_unit,
    descriptive_representation_item,
    envelope,
    envelope_relationship,
    interface_connection,
    interface_connector_definition,
    interface_definition_connection,
    interface_specification_definition,
    measure_representation_item,
    message_relationship,
    product_category,
    property_definition_relationship,
    structured_message,
    uncertainty_measure_with_unit);
END_TYPE;

  TYPE attribute_language_item_242 = SELECT BASED_ON attribute_language_item WITH
   (actuated_kinematic_pair,
    alternate_product_relationship,
    application_context,
    applied_certification_assignment,
    applied_identification_assignment,
    applied_security_classification_assignment,
    assembly_component_usage_substitute,
    attribute_value_assignment,
    configuration_design,
    configuration_item,
    data_environment,
    descriptive_representation_item,
    draughting_title,
    envelope,
    envelope_relationship,
    effectivity,
    effectivity_relationship,
    event_occurrence,
    evidence,
    external_source,
    general_property,
    general_property_relationship,
    geometric_representation_item,
    geometric_tolerance,
    group_relationship,
    interface_connection,
    interface_connector_occurrence,
    interface_definition_connection,
    interface_definition_for,
    kinematic_pair,
    make_from_usage_option,
    mapped_item,
    message_relationship,
    name_assignment,
    organization_role,
    person_and_organization_role,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_relationship,
    product_definition_context,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_shape,
    product_definition_substitute,
    product_group,
    product_group_relationship,
    product_related_product_category,
    property_definition,
    property_definition_relationship,
    representation,
    representation_relationship,
    security_classification,
    security_classification_assignment,
    shape_aspect,
    shape_aspect_relationship,
    shape_representation,
    structured_message,
    time_interval_role,
    topological_representation_item,
    presentation_layer_assignment,
    process_product_association,
    requirement_for_action_resource,
    resource_property,
    resource_requirement_type,
    styled_item,
    uncertainty_measure_with_unit,
    uncertainty_qualifier,
    versioned_action_request,
    versioned_action_request_relationship,
    validation,
    verification);
  END_TYPE;

  TYPE certification_item_242 = SELECT BASED_ON certification_item WITH
   (action_method,
    analysis_assignment,
    applied_action_method_assignment,
    assembly_component_usage,
    evidence,
    executed_action,
    interface_connection,
    interface_connector_version,
    interface_definition_connection,
    interface_specification_version,
    make_from_usage_option,
    organizational_project,
    product_definition,
    product_definition_formation,
    product_definition_occurrence,
    product_definition_occurrence_reference,
    product_definition_relationship,
    product_group,
    product_group_relationship,
    product_identification,
    product_relationship,
    requirement_view_definition_relationship
    );
END_TYPE;

  TYPE certified_item = SELECT
    (supplied_part_relationship);
  END_TYPE;

  TYPE change_request_item = SELECT
    (product_definition_formation);
  END_TYPE;

  TYPE cc_classified_item = SELECT
    (assembly_component_usage,
    product_definition_formation);
  END_TYPE;

  TYPE contract_item_242 = SELECT BASED_ON contract_item WITH
   (action_method,
    action_method_relationship,
    alternate_product_relationship,
    applied_action_method_assignment,
    applied_classification_assignment,
    applied_description_text_assignment,
    applied_external_identification_assignment,
    applied_identification_assignment,
    applied_organization_assignment,
    applied_person_and_organization_assignment,
    directed_action,
    drawing_revision,
    executed_action,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design,
    organization,
    person_and_organization,
    product,
    product_definition_context,
    product_definition_formation,
    product_group,
    product_group_relationship,
    product_identification,
    structured_message,
    validation,
    verification,
    versioned_action_request
    );
  END_TYPE;

  TYPE contracted_item = SELECT
    (product_definition_formation);
  END_TYPE;

  TYPE date_and_time_item_242 = SELECT BASED_ON date_and_time_item WITH
   (action_property,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    analysis_assignment,
    applied_organization_assignment,
    applied_person_and_organization_assignment,
    approval_person_organization,
    approval_status,
    assembly_component_usage_substitute,
    certification,
    class,
    class_system,
    configuration_design,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    directed_action,
    document,
    draughting_model,
    drawing_revision,
    event_occurrence,
    evidence,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design_to_planned,
    interface_connector_design_to_realized,
    interface_connector_occurrence,
    interface_connector_planned_to_realized,
    interface_definition_connection,
    interface_definition_for,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organizational_project,
    presentation_area,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_formation,
    product_definition_substitute,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_identification,
    requirement_for_action_resource,
    resource_property,
    security_classification,
    security_classification_level,
    shape_representation,
    validation,
    verification,
    verification_relationship);
  END_TYPE;

  TYPE date_item_242 = SELECT BASED_ON date_item WITH
   (action_property,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    analysis_assignment,
    applied_organization_assignment,
    applied_person_and_organization_assignment,
    approval_person_organization,
    approval_status,
    assembly_component_usage_substitute,
    certification,
    class,
    class_system,
    configuration_design,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    directed_action,
    document,
    draughting_model,
    drawing_revision,
    event_occurrence,
    evidence,
    executed_action,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design_to_planned,
    interface_connector_design_to_realized,
    interface_connector_occurrence,
    interface_connector_planned_to_realized,
    interface_definition_connection,
    interface_definition_for,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organizational_project,
    presentation_area,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_formation,
    product_definition_substitute,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_identification,
    requirement_for_action_resource,
    resource_property,
    security_classification,
    security_classification_level,
    shape_representation,
    validation,
    verification,
    verification_relationship);
  END_TYPE;

  TYPE date_time_item = SELECT
    (approval_person_organization,
    certification,
    change,
    change_request,
    contract,
    product_definition,
    security_classification,
    start_request,
    start_work);
  END_TYPE;

  TYPE document_reference_item_242 = SELECT BASED_ON document_reference_item WITH
   (action_directive,
    action_method_relationship,
    action_property,
    action_property_representation,
    action_relationship,
    analysis_assignment,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_classification_assignment,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_event_occurrence_assignment,
    applied_ineffectivity_assignment,
    applied_organizational_project_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    approval_person_organization,
    approval_relationship,
    assembly_component_usage,
    assembly_component_usage_substitute,
    breakdown_context,
    breakdown_of,
    change_group,
    characterized_object,
    class,
    class_system,
    condition,
    configuration_design,
    date_and_time_assignment,
    date_assignment,
    descriptive_representation_item,
    directed_action_assignment,
    document_relationship,
    effectivity_relationship,
    evaluated_characteristic_of_product_as_individual_test_result,
    evidence,
    exclusive_product_concept_feature_category,
    externally_defined_item,
    feature_definition,
    frozen_assignment,
    identification_assignment_relationship,
    in_zone,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design,
    interface_connector_design_to_planned,
    interface_connector_design_to_realized,
    interface_connector_occurrence,
    interface_connector_planned_to_realized,
    interface_definition_connection,
    material_designation_characterization,
    measure_representation_item,
    organization_relationship,
    organizational_address,
    organizational_project_relationship,
    package_product_concept_feature,
    person_and_organization,
    person_and_organization_address,
    presentation_area,
    process_plan,
    product,
    product_category,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_context,
    product_definition_formation,
    product_definition_group_assignment,
    product_definition_process,
    product_definition_relationship,
    product_definition_substitute,
    product_definition_usage,
    product_design_to_individual,
    product_design_version_to_individual,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_process_plan,
    product_related_product_category,
    product_relationship,
    property_definition_representation,
    representation_relationship,
    requirement_for_action_resource,
    resource_requirement_type,
    retention,
    state_observed,
    state_type,
    structured_message,
    time_interval,
    time_interval_relationship,
    validation,
    value_representation_item,
    verification,
    verification_relationship);
  END_TYPE;

  TYPE effectivity_item_242 = SELECT BASED_ON effectivity_item WITH
   (action,
    action_directive,
    action_directive_relationship,
    action_method,
    action_method_relationship,
    action_property,
    action_property_representation,
    action_relationship,
    alternative_solution_relationship,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_classification_assignment_relationship,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_external_identification_assignment_relationship,
    applied_ineffectivity_assignment,
    applied_person_and_organization_assignment,
    applied_time_interval_assignment,
    approval_relationship,
    assembly_component_usage_substitute,
    assignment_object_relationship,
    breakdown_of,
    class,
    class_system,
    condition,
    conditional_effectivity,
    configuration_design,
    configuration_item,
    configuration_item_relationship,
    contract,
    directed_action_assignment,
    document_relationship,
    draughting_model,
    drawing_revision,
    effectivity_relationship,
    event_occurrence_relationship,
    evidence,
    exclusive_product_concept_feature_category,
    executed_action,
    externally_defined_general_property,
    frozen_assignment,
    general_property,
    general_property_relationship,
    generic_property_relationship,
    geometric_tolerance,
    group,
    identification_assignment_relationship,
    in_zone,
    inclusion_product_concept_feature,
    interface_connection,
    interface_connector_design_to_planned,
    interface_connector_design_to_realized,
    interface_connector_occurrence,
    interface_connector_planned_to_realized,
    interface_definition_for,
    link_motion_relationship,
    material_designation,
    material_designation_characterization,
    measure_representation_item,
    mechanical_design_geometric_presentation_representation,
    organization,
    organizational_project,
    organizational_project_relationship,
    package_product_concept_feature,
    presentation_area,
    process_operation,
    process_plan,
    product,
    product_class,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_concept_relationship,
    product_definition,
    product_definition_formation,
    product_definition_relationship,
    product_definition_usage,
    product_definition_usage_relationship,
    product_design_to_individual,
    product_design_version_to_individual,
    product_identification,
    product_process_plan,
    product_relationship,
    property_definition_representation,
    representation,
    representation_relationship,
    requirement_for_action_resource,
    resource_property,
    security_classification,
    shape_aspect,
    shape_aspect_relationship,
    shape_representation,
    structured_message,
    time_interval_relationship,
    usage_association,
    validation,
    value_representation_item,
    verification,
    verification_relationship,
    versioned_action_request_relationship
     );
  END_TYPE;

  TYPE event_occurrence_item_242 = SELECT BASED_ON event_occurrence_item WITH
   (action,
    action_directive,
    action_method,
    action_property,
    action_request_solution,
    alternate_product_relationship,
    applied_action_assignment,
    applied_classification_assignment,
    assembly_component_usage_substitute,
    class,
    class_system,
    configuration_design,
    configuration_effectivity,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    draughting_model,
    drawing_revision,
    executed_action,
    general_property,
    general_organizational_data_select,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organization_relationship,
    organizational_project,
    person_and_organization,
    presentation_area,
    product,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_relationship,
    product_definition_substitute,
    property_definition,
    requirement_for_action_resource,
    resource_property,
    security_classification_level,
    shape_representation);
  END_TYPE;

  TYPE external_identification_item_242 = SELECT BASED_ON external_identification_item WITH
   (action_directive,
    action_method,
    action_method_relationship,
    address,
    analysis_model,
    analysis_representation_context,
    applied_action_method_assignment,
    applied_classification_assignment,
    approval,
    approval_person_organization,
    assembly_component_usage,
    breakdown_context,
    certification,
    class,
    composite_curve,
    condition,
    configuration_effectivity,
    contract,
    curve,
    derived_unit,
    document_file,
    effectivity,
    evaluated_characteristic_of_product_as_individual_test_result,
    event_occurrence,
    evidence,
    exclusive_product_concept_feature_category,
    executed_action,
    externally_defined_context_dependent_unit,
    externally_defined_general_property,
    general_property,
    group,
    information_right,
    information_usage_right,
    interface_connection,
    interface_connector_definition,
    interface_connector_occurrence,
    interface_connector_version,
    interface_definition_connection,
    interface_definition_for,
    interface_specification_definition,
    interface_specification_version,
    loop,
    material_designation,
    named_unit,
    organization,
    organizational_project,
    oriented_surface,
    package_product_concept_feature,
    person,
    person_and_organization,
    point_on_curve,
    precision_qualifier,
    process_operation,
    process_plan,
    product,
    product_concept,
    product_concept_context,
    product_concept_feature,
    product_concept_feature_category,
    product_definition,
    product_definition_context,
    product_definition_formation,
    product_definition_occurrence,
    product_definition_occurrence_reference,
    product_group,
    product_identification,
    product_process_plan,
    product_specification,
    property_definition,
    representation,
    representation_item,
    requirement_source,
    satisfies_requirement,
    security_classification,
    shape_representation,
    state_observed,
    state_type,
    structured_message,
    surface,
    time_interval,
    type_qualifier,
    uncertainty_qualifier,
    validation,
    verification,
    versioned_action_request,
    vertex_point
    );
  END_TYPE;

TYPE ap242_evidence_item = SELECT BASED_ON evidence_item WITH
    (action_property,
     action_property_representation,
     analysis_assignment,
     applied_action_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_classification_assignment,
     applied_contract_assignment,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_external_identification_assignment,
     applied_ineffectivity_assignment,
     applied_organization_assignment,
     applied_organizational_project_assignment,
     applied_person_and_organization_assignment,
     applied_security_classification_assignment,
     date_and_time_assignment,
     date_assignment,
     measure_representation_item,
     person,
     person_and_organization,
     product,
     product_definition,
     product_definition_context,
     product_definition_formation,
     product_definition_formation_relationship,
     product_definition_relationship,
     product_relationship,
     property_definition,
     property_definition_representation,
     representation,
     representation_context,
     representation_item,
     state_type,
     structured_message,
     value_representation_item);
END_TYPE;

  TYPE groupable_item_242 = SELECT BASED_ON groupable_item WITH
    (class,
     geometric_representation_item,
     general_property,
     interface_connector_definition,
     mapped_item,
     product_definition,
     representation_relationship_with_transformation,
     same_as_external_item_assignment,
     shape_aspect,
     shape_representation_relationship,
     styled_item,
     topological_representation_item);
  END_TYPE;
  
TYPE general_organizational_data_select = SELECT
	(action_directive,
     action_method,
     action_method_relationship,
     action_property,
     action_property_representation,
     action_relationship,
     action_request_solution,
     alternate_product_relationship,
     alternative_solution_relationship,
     applied_action_assignment,
     applied_action_method_assignment,
     applied_action_request_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_classification_assignment,
     applied_contract_assignment,
     applied_description_text_assignment,
     applied_description_text_assignment_relationship,
     applied_document_reference,
     applied_document_usage_constraint_assignment,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_external_identification_assignment,
     applied_identification_assignment,
     applied_ineffectivity_assignment,
     applied_organization_assignment,
     applied_organizational_project_assignment,
     applied_person_and_organization_assignment,
     applied_security_classification_assignment,
     applied_time_interval_assignment,
     applied_usage_right,
     approval,
     approval_person_organization,
     approval_relationship,
     approval_status,
     assembly_component_usage,
     assembly_component_usage_substitute,
     breakdown_element_group_assignment,
     breakdown_element_realization,
     breakdown_of,
     certification,
     characterized_product_concept_feature,
     characterized_product_concept_feature_category,
     class,
     class_system,
     condition,
     conditional_concept_feature,
     conditional_effectivity,
     configuration_design,
     configuration_effectivity,
     configuration_item,
     configured_effectivity_assignment,
     contract,
     date_and_time_assignment,
     date_assignment,
     directed_action_assignment,
     document_file,
     drawing_revision,
     drawing_sheet_revision,
     effectivity,
     evaluated_characteristic_of_product_as_individual_test_result,
     exclusive_product_concept_feature_category,
     executed_action,
     frozen_assignment,
     general_property,
     general_property_relationship,
     group,
     group_relationship,
     identification_assignment_relationship,
     inclusion_product_concept_feature,
     information_usage_right,
     material_designation,
     material_designation_characterization,
     measure_representation_item,
     organization,
     organization_relationship,
     organizational_address,
     organizational_project,
     package_product_concept_feature,
     person,
     person_and_organization,
     person_and_organization_address,
     presentation_area,
     process_operation,
     process_plan,
     product,
     product_class,
     product_concept,
     product_concept_feature,
     product_concept_feature_association,
     product_concept_feature_category,
     product_concept_feature_category_usage,
     product_definition,
     product_definition_formation,
     product_definition_formation_relationship,
     product_definition_group_assignment,
     product_definition_occurrence,
     product_definition_occurrence_reference,
     product_definition_relationship,
     product_definition_substitute,
     product_definition_usage,
     product_design_to_individual,
     product_design_version_to_individual,
     product_process_plan,
     product_relationship,
     property_definition,
     property_definition_representation,
     representation,
     representation_item,
     representation_relationship,
     requirement_assignment,
     requirement_for_action_resource,
     requirement_source,
     requirement_view_definition_relationship,
     security_classification,
     shape_representation,
     value_representation_item,
     versioned_action_request
     );
END_TYPE;

  TYPE identification_item_242 = SELECT BASED_ON identification_item WITH
    (action_directive,
     action_directive_relationship,
     action_method,
     action_method_relationship,
     action_property,
     action_property_representation,
     action_relationship,
     alternate_product_relationship,
     alternative_solution_relationship,
     analysis_assignment,
     analysis_representation_context,
     applied_action_assignment,
     applied_action_method_assignment,
     applied_action_request_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_classification_assignment_relationship,
     applied_contract_assignment,
     applied_description_text_assignment,
     applied_description_text_assignment_relationship,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_external_identification_assignment,
     applied_external_identification_assignment_relationship,
     applied_identification_assignment,
     applied_ineffectivity_assignment,
     applied_organizational_project_assignment,
     applied_person_and_organization_assignment,
     applied_time_interval_assignment,
     applied_usage_right,
     approval_relationship,
     approval_status,
     assembly_component_usage,
     assembly_component_usage_substitute,
     assignment_object_relationship,
     breakdown_element_realization,
     breakdown_of,
     change_group,
     class,
     class_system,
     characterized_class,
     configuration_effectivity,
     configuration_item_relationship,
     contract_relationship,
     date_and_time_assignment,
     date_assignment,
     degenerate_pcurve,
     dimensional_size,
     dimensional_size_with_path,
     directed_action_assignment,
     document_file,
     document_relationship,
     draughting_model,
     effectivity_relationship,
     envelope,
     envelope_relationship,
     evaluated_characteristic,
     event_occurrence_relationship,
     evidence,
     exclusive_product_concept_feature_category,
     executed_action,
     general_property,
     generic_property_relationship,
     identification_assignment_relationship,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_definition,
     interface_connector_design,
     interface_connector_occurrence,
     interface_connector_version,
     interface_definition_connection,
     interface_definition_for,
     interface_specification_definition,
     interface_specification_version,
     link_motion_relationship,
     material_designation_characterization,
     measure_representation_item,
     mechanical_design_geometric_presentation_representation,
     message_relationship,
     organization,
     organization_relationship,
     organizational_address,
     organizational_project_relationship,
     package_product_concept_feature,
     person_and_organization_address,
     point_on_surface,
     presentation_area,
     process_operation,
     process_plan,
     product,
     product_category,
     product_concept_context,
     product_concept_feature,
     product_concept_feature_category,
     product_concept_relationship,
     product_definition,
     product_definition_formation,
     product_definition_formation_relationship,
     product_definition_occurrence,
     product_definition_occurrence_reference,
     product_definition_relationship,
     product_definition_usage,
     product_definition_usage_relationship,
     product_group,
     product_group_membership,
     product_group_relationship,
     product_process_plan,
     product_relationship,
     property_definition_relationship,
     property_definition_representation,
     representation,
     representation_context,
     representation_relationship,
     requirement_for_action_resource,
     retention,
     satisfies_requirement,
     security_classification,
     security_classification_level,
     shape_aspect,
     shape_feature_definition,
     shape_feature_definition_relationship,
     shape_representation,
     state_definition_to_state_assignment_relationship,
     structured_message,
     time_interval,
     time_interval_relationship,
     validation,
     verification,
     verification_relationship,
     versioned_action_request,
     versioned_action_request_relationship
     );
  END_TYPE;

  TYPE multi_language_attribute_item_242 = SELECT BASED_ON multi_language_attribute_item WITH
    (action_directive_relationship,
     action_directive,
     action_method_relationship,
     action_method,
     action_property,
     action_property_representation,
     action_relationship,
     actuated_kinematic_pair,
     alternate_product_relationship,
     alternative_solution_relationship,
     analysis_assignment,
     analysis_representation_context,
     application_context,
     applied_action_assignment,
     applied_action_method_assignment,
     applied_action_request_assignment,
     applied_approval_assignment,
     applied_certification_assignment,
     applied_classification_assignment_relationship,
     applied_contract_assignment,
     applied_description_text_assignment_relationship,
     applied_description_text_assignment,
     applied_effectivity_assignment,
     applied_event_occurrence_assignment,
     applied_external_identification_assignment_relationship,
     applied_identification_assignment,
     applied_ineffectivity_assignment,
     applied_organization_assignment,
     applied_person_and_organization_assignment,
     applied_time_interval_assignment,
     applied_usage_right,
     ascribable_state,
     ascribable_state_relationship,
     assembly_component_usage_substitute,
     assignment_object_relationship,
     attribute_value_assignment,
     breakdown_context,
     breakdown_element_realization,
     breakdown_of,
     change_element_sequence,
     change_group,
     class,
     colour,
     configuration_design,
     configuration_effectivity,
     configuration_item_relationship,
     configuration_item,
     contract_relationship,
     data_environment,
     descriptive_representation_item,
     directed_action_assignment,
     document_file,
     draughting_title,
     effectivity_relationship,
     effectivity,
     envelope_relationship,
     envelope,
     evaluated_characteristic,
     event_occurrence_relationship,
     event_occurrence,
     evidence,
     executed_action,
     exclusive_product_concept_feature_category,
     external_source,
     externally_defined_class,
     general_property_relationship,
     general_property,
     generic_property_relationship,
     geometric_representation_item,
     geometric_tolerance,
     global_uncertainty_assigned_context,
     global_unit_assigned_context,
     group_relationship,
     group,
     identification_assignment_relationship,
     in_zone,
     interface_connection,
     interface_connector_occurrence,
     interface_definition_connection,
     interface_definition_for,
     kinematic_pair,
     link_motion_relationship,
     make_from_usage_option,
     mapped_item,
     material_designation_characterization,
     measure_qualification,
     measure_with_unit,
     message_relationship,
     name_assignment,
     organization_role,
     organization,
     organizational_address,
     package_product_concept_feature,
     person_and_organization_address,
     person_and_organization_role,
     person,
     presentation_layer_assignment,
     process_operation,
     process_plan,
     process_product_association,
     product_concept_context,
     product_concept_feature_association,
     product_concept_feature_category_usage,
     product_concept_feature_category,
     product_concept_feature,
     product_concept_relationship,
     product_concept,
     product_definition_context,
     product_definition_formation_relationship,
     product_definition_formation,
     product_definition_relationship,
     product_definition_shape,
     product_definition_substitute,
     product_definition_usage_relationship,
     product_definition_usage,
     product_design_to_individual,
     product_design_version_to_individual,
     product_group_relationship,
     product_group,
     product_identification,
     product_process_plan,
     product_related_product_category,
     product_relationship,
     product_specification,
     property_definition_relationship,
     property_definition_representation,
     property_definition,
     qualitative_uncertainty,
     representation_context,
     representation_relationship_with_transformation,
     representation_relationship,
     representation,
     requirement_for_action_resource,
     resource_property,
     resource_requirement_type,
     retention,
     satisfies_requirement,
     security_classification_assignment,
     security_classification,
     shape_aspect_relationship,
     shape_aspect,
     shape_feature_definition_relationship,
     shape_feature_definition,
     shape_representation,
     state_definition_to_state_assignment_relationship,
     state_observed_assignment,
     state_type_assignment,
     structured_message,
     styled_item,
     time_interval_relationship,
     time_interval_role,
     time_interval,
     topological_representation_item,
     uncertainty_measure_with_unit,
     uncertainty_qualifier,
     validation,
     verification_relationship,
     verification,
     versioned_action_request_relationship,
     versioned_action_request
    );
  END_TYPE;

  TYPE organization_item_242 = SELECT BASED_ON organization_item WITH
   (action_property,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    applied_action_assignment,
    applied_identification_assignment,
    applied_security_classification_assignment,
    approval_status,
    assembly_component_usage_substitute,
    certification,
    class_system,
    configuration_design,
    configured_effectivity_assignment,
    datum,
    datum_system,
    dimensional_location,
    dimensional_size,
    document_file,
    document_type,
    draughting_model,
    drawing_revision,
    event_occurrence,
    evidence,
    general_property,
    geometric_tolerance,
    information_right,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_occurrence,
    interface_definition_connection,
    interface_definition_for,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organization,
    organization_relationship,
    organizational_project,
    product,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_substitute,
    product_group,
    product_group_membership,
    product_group_relationship,
    property_definition,
    satisfies_requirement,
    security_classification_level,
    shape_representation,
    structured_message,
    presentation_area,
    requirement_for_action_resource,
    resource_property,
    validation,
    verification);
  END_TYPE;

  TYPE organizational_project_item_242 = SELECT BASED_ON project_item WITH
   (action_method,
    action_method_relationship,
    applied_action_assignment,
    applied_action_method_assignment,
    assembly_component_usage,
    executed_action,
    product_concept,
    product_definition,
    product_definition_formation,
    product_definition_occurrence,
    product_definition_occurrence_reference,
    property_definition_representation,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_identification,
    measure_representation_item,
    representation,
    representation_item,
    value_representation_item
    );
  END_TYPE;
  
  (*BZ 7265
  TYPE ap242_interface_component_item = SELECT BASED_ON interface_component_item WITH (
    interface_definition_connection);
  END_TYPE;
*)

  TYPE ap242_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
   (action_method,
    alternate_product_relationship,
    applied_action_method_assignment,
    applied_state_observed_assignment,
    applied_state_type_assignment,
    assembly_component_usage,
    assembly_component_usage_substitute,
    descriptive_representation_item,
    interface_connector_occurrence,
    organizational_project,
    product_definition_group_assignment,
    product_group,
    product_group_membership,
    quantified_assembly_component_usage,
    representation,
    state_observed,
    state_type,
    validation,
    verification,
    versioned_action_request);
  END_TYPE;


  TYPE ap242_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
    (action_method,
     applied_action_method_assignment,
     applied_state_observed_assignment,
     applied_state_type_assignment,
     contract,
     executed_action,
     interface_connector_occurrence,
     organization,
     organizational_project,
     person_and_organization,
     product_definition_formation,
     state_observed,
     state_type,
     validation,
     verification);
  END_TYPE;

  TYPE person_and_organization_item_242 = SELECT BASED_ON person_and_organization_item WITH
   (action_property,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    applied_action_assignment,
    applied_security_classification_assignment,
    approval_status,
    assembly_component_usage_substitute,
    certification,
    class,
    class_system,
    configuration_design,
    configuration_effectivity,
    configured_effectivity_assignment,
    datum,
    datum_system,
    dimensional_location,
    dimensional_size,
    document_file,
    document_type,
    draughting_model,
    drawing_revision,
    evidence,
    general_property,
    geometric_tolerance,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_occurrence,
    interface_definition_connection,
    interface_definition_for,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organization,
    organization_relationship,
    organizational_project,
    presentation_area,
    product,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_substitute,
    product_group,
    product_group_membership,
    product_group_relationship,
    property_definition,
    requirement_for_action_resource,
    resource_property,
    security_classification_level,
    shape_representation,
    structured_message,
    validation,
    verification);
  END_TYPE;

  TYPE project_item_242 = SELECT BASED_ON project_item WITH
   (configuration_item);
  END_TYPE;

TYPE ap242_product_definition_or_product_definition_relationship = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON product_definition_or_product_definition_relationship WITH
   (interface_connector_occurrence,
   product,
   product_group);
END_TYPE;
(*
  TYPE property_variable_rep_select_242 = SELECT BASED_ON property_variable_rep_select WITH (
     dimensional_size,
     dimensional_location,
     representation);
  END_TYPE;
*)
  TYPE cc_person_organization_item = SELECT
    (change,
    change_request,
    configuration_item,
    contract,
    product,
    product_definition,
    product_definition_formation,
    security_classification,
    start_request,
    start_work);
  END_TYPE;

TYPE ap242_validation_groupable_item = SELECT BASED_ON validation_groupable_item WITH
   (action_method,
    applied_organization_assignment,
    applied_person_and_organization_assignment,
    state_type);
END_TYPE;


  TYPE presented_item_select_242 = SELECT BASED_ON presented_item_select WITH
    (action,
    action_method,
    action_relationship,
    product_concept,
    product_concept_feature,
    product_concept_feature_category,
    product_definition,
    product_definition_formation,
    product_definition_relationship);
  END_TYPE;

  TYPE ap242_requirement_representation_proxy_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_representation_proxy_select WITH
   (product_definition_formation);
  END_TYPE;
  
  TYPE ap242_instance_usage_context_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON instance_usage_context_select WITH
  	(product_definition_group_assignment,
     process_product_association,
     product_definition_usage);
  END_TYPE;

  TYPE same_as_item_242 = SELECT BASED_ON same_as_item WITH
   (address,
    applied_external_identification_assignment,
    approval,
    approval_status,
    attribute_language_assignment,
    calendar_date,
    certification,
    contract,
    coordinated_universal_time_offset,
    date_and_time,
    derived_unit,
    derived_unit_element,
    event_occurrence,
    external_source,
    general_property,
    information_right,
    information_usage_right,
    language,
    local_time,
    measure_with_unit,
    named_unit,
    organization,
    person,
    product_definition_context,
    representation_context,
    requirement_source,
    security_classification,
    time_interval,
    usage_association);
  END_TYPE;

  TYPE security_classification_item_242 = SELECT BASED_ON security_classification_item WITH
   (action,
    action_directive,
    action_method,
    action_method_relationship,
    action_property,
    action_property_representation,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_classification_assignment,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_external_identification_assignment,
    applied_identification_assignment,
    assembly_component_usage_substitute,
    class_system,
    conditional_effectivity,
    configuration_design,
    configuration_effectivity,
    configured_effectivity_assignment,
    document,
    document_file,
    draughting_model,
    drawing_revision,
    evaluated_characteristic_of_product_as_individual_test_result,
    envelope,
    evidence,
    exclusive_product_concept_feature_category,
    executed_action,
    externally_defined_general_property,
    general_property,
    group,
    identification_assignment_relationship,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design,
    interface_connector_occurrence,
    interface_definition_connection,
    interface_definition_for,
    make_from_usage_option,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organizational_project,
    package_product_concept_feature,
    presentation_area,
    process_plan,
    product,
    product_class,
    product_concept,
    product_concept_feature,
    product_concept_feature_category,
    product_definition,
    product_definition_formation,
    product_definition_group_assignment,
    product_definition_relationship,
    product_definition_usage,
    product_design_to_individual,
    product_design_version_to_individual,
    product_group,
    product_group_membership,
    product_group_relationship,
    product_identification,
    product_process_plan,
    product_relationship,
    property_definition,
    property_definition_representation,
    representation,
    requirement_view_definition_relationship,
    resource_property,
    shape_representation,
    validation,
    verification,
    versioned_action_request);
  END_TYPE;


TYPE ap242_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
    (alternate_product_relationship,
    applied_action_method_assignment,
    applied_external_identification_assignment,
    approval,
    assembly_component_usage,
    assembly_component_usage_substitute,
    attachment_slot_design_to_planned,
    attachment_slot_design_to_realized,
    attachment_slot_on_product,
    attachment_slot_planned_to_realized,
    breakdown_element_group_assignment,
    breakdown_element_usage,
    certification,
    configuration_item,
    contract,
    document_file,
    evidence,
    final_solution,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_definition,
    interface_connector_design,
    interface_connector_occurrence,
    interface_connector_version,
    interface_definition_connection,
    interface_specification_definition,
    interface_specification_version,
    organization,
    organizational_project,
    person_and_organization,
    product,
    product_category,
    product_concept,
    product_definition,
    product_definition_formation,
    product_definition_group_assignment,
    product_definition_relationship,
    product_in_attachment_slot,
    security_classification,
    validation,
    verification);
END_TYPE;

TYPE ap242_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
   (action_method,
    alternate_product_relationship,
    applied_action_method_assignment,
    applied_external_identification_assignment,
    approval,
    assembly_component_usage,
    assembly_component_usage_substitute,
    attachment_slot_design_to_planned,
    attachment_slot_design_to_realized,
    attachment_slot_on_product,
    attachment_slot_planned_to_realized,
    breakdown_element_group_assignment,
    breakdown_element_usage,
    certification,
    configuration_item,
    contract,
    document_file,
    evidence,
    final_solution,
    interface_connection,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_definition,
    interface_connector_design,
    interface_connector_occurrence,
    interface_connector_version,
    interface_definition_connection,
    interface_specification_definition,
    interface_specification_version,
    organization,
    organizational_project,
    person_and_organization,
    product,
    product_category,
    product_concept,
    product_definition,
    product_definition_formation,
    product_definition_group_assignment,
    product_definition_relationship,
    product_group,
    product_in_attachment_slot,
    security_classification,
    validation,
    verification);
END_TYPE;


  TYPE cc_specified_item = SELECT
    (product_definition,
    shape_aspect);
  END_TYPE;

  TYPE start_request_item = SELECT
    (product_definition_formation);
  END_TYPE;

  TYPE time_interval_item_242 = SELECT BASED_ON time_interval_item WITH
   (action_directive,
    action_method,
    action_property,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    analysis_assignment,
    applied_action_assignment,
    applied_classification_assignment,
    applied_person_and_organization_assignment,
    approval_status,
    assembly_component_usage_substitute,
    certification,
    class,
    class_system,
    configuration_design,
    configuration_effectivity,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    document_file,
    draughting_model,
    drawing_revision,
    evidence,
    executed_action,
    general_property,
    material_designation,
    mechanical_design_geometric_presentation_representation,
    organization_relationship,
    organizational_project,
    person_and_organization,
    presentation_area,
    product,
    product_concept,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_definition,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_relationship,
    product_definition_substitute,
    property_definition,
    requirement_for_action_resource,
    resource_property,
    security_classification,
    security_classification_level,
    shape_representation,
    time_interval_based_effectivity,
    validation,
    verification,
    verification_relationship,
    versioned_action_request);
  END_TYPE;

  TYPE action_items_242 = SELECT BASED_ON action_items WITH
   (action,
    action_directive,
    action_directive_relationship,
    action_property,
    action_property_representation,
    action_method,
    action_method_relationship,
    action_relationship,
    action_request_solution,
    alternate_product_relationship,
    alternative_solution_relationship,
    analysis_assignment,
    applied_action_assignment,
    applied_action_method_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_classification_assignment,
    applied_contract_assignment,
    applied_description_text_assignment,
    applied_description_text_assignment_relationship,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_organization_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_state_observed_assignment,
    applied_time_interval_assignment,
    approval,
    approval_relationship,
    approval_status,
    ascribable_state,
    ascribable_state_relationship,
    assembly_component_usage_substitute,
    assignment_object_relationship,
    breakdown_of,
    certification,
    certification_item,
    change_group,
    characterized_class,  
    class,
    class_system,
    classification_item,
    condition,
    conditional_effectivity,
    configuration_design,
    configuration_item_relationship,
    configuration_item,
    configured_effectivity_assignment,
    contract,
    date_and_time_assignment,
    date_assignment,
    directed_action_assignment,
    document_file,
    document_reference_item,
    document_relationship,
    draughting_model,
    drawing_revision,
    effectivity,
    effectivity_relationship,
    evaluated_characteristic_of_product_as_individual_test_result,
    event_occurrence,
    evidence,
    exclusive_product_concept_feature_category,
    executed_action,
    frozen_assignment,
    general_property,
    general_property_relationship,
    group,
    group_relationship,
    identification_assignment_relationship,
    identification_item,
    inclusion_product_concept_feature,
    information_right,
    information_usage_right,
    interface_connector_as_planned,
    interface_connector_as_realized,
    interface_connector_design,
    interface_connector_version,
    interface_definition_for,
    interface_specification_version,
    material_designation,
    material_designation_characterization,
    measure_representation_item,
    mechanical_design_geometric_presentation_representation,
    observation_consequence,
    organization,
    organization_relationship,
    organizational_address,
    organizational_project,
    organizational_project_relationship,
    package_product_concept_feature,
    person,
    person_and_organization,
    person_and_organization_address,
    presentation_area,
    process_operation,
    process_plan,
    product,
    product_category,
    product_class,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
    product_concept_feature_category_usage,
    product_concept_relationship,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_group_assignment,
    product_definition_occurrence,
    product_definition_relationship,
    product_definition_substitute,
    product_definition_usage,
    product_group_membership,
    product_identification,
    product_process_plan,
    product_relationship,
    property_definition,
    property_definition_representation,
    representation,
    representation_item,
    representation_relationship,
    requirement_assigned_item,
    requirement_for_action_resource,
    requirement_view_definition_relationship,
    resource_property,
    retention,
    rule_set,
    security_classification_level,
    shape_aspect,
    shape_aspect_relationship,
    shape_representation,
    state_observed_assignment,
    state_observed_relationship,
    state_type_assignment,
    state_type_relationship,
    structured_message,
    usage_association,
    validation,
    value_representation_item,
    verification,
    verification_relationship,
    versioned_action_request,
    versioned_action_request_relationship);
  END_TYPE;

  TYPE classification_item_242 = SELECT BASED_ON classification_item WITH
   (action_directive_relationship,
    action_method_relationship,
    action_property_representation,
     action_relationship,
     alternative_solution_relationship,
     analysis_assignment,
     applied_action_method_assignment,
     applied_classification_assignment_relationship,
     applied_description_text_assignment_relationship,
     applied_description_text_assignment,
     applied_external_identification_assignment_relationship,
     applied_ineffectivity_assignment,
     applied_person_and_organization_assignment,
     applied_time_interval_assignment,
     assignment_object_relationship,
     breakdown_context,
     breakdown_element_realization,
     breakdown_of,
     change_element_sequence,
     change_group,
     characterized_class,
     configuration_design,
     configuration_effectivity,
     configuration_item_relationship,
     definitional_representation_relationship,
    directed_action_assignment,
    document_type,
     envelope_relationship,
     envelope,
     evaluated_characteristic,
     evidence,
     feature_definition,
     general_feature,
     general_property,
     generic_property_relationship,
     group_relationship,
     identification_assignment_relationship,
     in_zone,
     interface_connection,
     interface_connector_as_planned,
     interface_connector_as_realized,
     interface_connector_design_to_planned,
     interface_connector_design_to_realized,
     interface_connector_design,
     interface_connector_occurrence,
     interface_connector_planned_to_realized,
     interface_definition_connection,
     interface_definition_for,
    link_motion_relationship,
    material_designation,
     material_designation_characterization,
     measure_qualification,
     message_relationship,
     plus_minus_tolerance,
     process_operation,
     process_plan,
     process_product_association,
      product_concept_context,
    product_concept_feature,
    product_concept_feature_association,
    product_concept_feature_category,
     product_concept_feature_category_usage,
     product_concept_relationship,
     product_definition_formation,
     product_definition_relationship,
     product_definition_usage_relationship,
     product_definition_usage,
     product_design_to_individual,
     product_design_version_to_individual,
     product_group_membership,
     product_process_plan,
     product_relationship,
     property_definition_representation,
     representation,
     representation_relationship,
     requirement_for_action_resource,
     resource_property,
     retention,
     satisfies_requirement,
    security_classification_level,
    shape_aspect_relationship,
     shape_aspect,
     shape_feature_definition_relationship,
     state_definition_to_state_assignment_relationship,
     structured_message,
     type_qualifier,
     validation,
     verification,
     versioned_action_request_relationship);
END_TYPE;


TYPE ap242_collection_assignment_groupable_item = SELECT BASED_ON collection_assignment_groupable_item WITH
   (contract,
    organization,
    organizational_project,
    product,
    product_concept,
    product_definition,
    product_definition_formation);
END_TYPE;

TYPE ap242_collection_membership_groupable_item = SELECT BASED_ON collection_membership_groupable_item WITH
   (address,
    alternate_product_relationship,
    applied_action_assignment,
    applied_action_request_assignment,
    applied_approval_assignment,
    applied_attribute_classification_assignment,
    applied_certification_assignment,
    applied_classification_assignment,
    applied_contract_assignment,
    applied_description_text_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment,
    applied_external_identification_assignment,
    applied_group_assignment,
    applied_identification_assignment,
    applied_location_assignment,
    applied_location_representation_assignment,
    applied_name_assignment,
    applied_organization_assignment,
    applied_organization_type_assignment,
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    approval,
    approval_person_organization,
    approval_relationship,
    approval_status,
    ascribable_state,
    ascribable_state_relationship,
    assembly_component_usage_substitute,
    attribute_language_assignment,
    breakdown_element_group_assignment,
    calendar_date,
    certification,
    configuration_design,
    configuration_item,
    configuration_item_relationship,
    context_dependent_shape_representation,
    contract,
    contract_relationship,
    coordinated_universal_time_offset,
    date_and_time,
    date_and_time_assignment,
    date_assignment,
    derived_unit,
    derived_unit_element,
    description_text,
    document_file,
    document_relationship,
    effectivity,
    effectivity_relationship,
    event_occurrence,
    event_occurrence_relationship,
    evidence,
    external_source,
    general_property,
    general_property_relationship,
    geometric_item_specific_usage,
    item_defined_transformation,
    local_time,
    measure_qualification,
    measure_with_unit,
    multi_language_attribute_assignment,
    named_unit,
    organization,
    organization_relationship,
    organization_type,
    organizational_project,
    organizational_project_relationship,
    person,
    person_and_organization,
    precision_qualifier,
    product,
    product_concept,
    product_concept_context,
    product_definition,
    product_definition_context,
    product_definition_formation,
    product_definition_formation_relationship,
    product_definition_group_assignment,
    product_definition_relationship,
    product_group_membership,
    product_group_relationship,
    product_relationship,
    property_definition,
    property_definition_representation,
    representation,
    representation_context,
    representation_item,
    representation_relationship,
    security_classification,
    shape_aspect,
    shape_aspect_relationship,
    state_observed,
    state_observed_assignment,
    state_observed_relationship,
    state_observed_role,
    state_type,
    state_type_assignment,
    state_type_relationship,
    time_interval,
    time_interval_assignment,
    time_interval_relationship,
    time_interval_role,
    type_qualifier,
    uncertainty_qualifier,
    verification_relationship,
    versioned_action_request);
END_TYPE;

TYPE ap242_condition_evaluation_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_evaluation_action_items WITH
   (applied_approval_assignment,
    applied_certification_assignment,
    applied_classification_assignment,
    applied_contract_assignment,
    applied_date_and_time_assignment,
    applied_date_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_identification_assignment,
    applied_organization_assignment,
    applied_person_and_organization_assignment,
    approval,
    calendar_date,
    date_and_time,
    hierarchical_interface_connection,
    interface_connection,
    interface_connector_occurrence,
    interface_definition_connection,
    product,
    product_concept,
    product_definition,
	product_definition_element_relationship,
    product_definition_formation,
	product_definition_relationship,
	product_group,
    product_group_membership,
    product_group_relationship,
    product_related_product_category,
    property_definition,
    property_definition_representation,
    representation,
    state_observed,
    state_type);
END_TYPE;

  TYPE configured_effectivity_item_242 = SELECT BASED_ON configured_effectivity_item WITH
   (action_relationship,
    process_plan,
    product_process_plan);
  END_TYPE;

  TYPE work_item = SELECT
    (product_definition_formation);
  END_TYPE;
  
  TYPE observed_context_item_242 = SELECT BASED_ON observed_context_item WITH
  	(action,
	action_directive,
	action_directive_relationship,
	action_method,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_relationship,
	action_request_solution,
	alternate_product_relationship,
	alternative_solution_relationship,
	analysis_assignment,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_action_request_assignment,
	applied_approval_assignment,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	applied_date_and_time_assignment,
	applied_date_assignment,
	applied_description_text_assignment,
	applied_description_text_assignment_relationship,
	applied_document_reference,
	applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	applied_external_identification_assignment,
	applied_identification_assignment,
	applied_ineffectivity_assignment,
	applied_organization_assignment,
	applied_organizational_project_assignment,
	applied_person_and_organization_assignment,
	applied_security_classification_assignment,
	applied_state_observed_assignment,
	applied_state_type_assignment,
	applied_time_interval_assignment,
	applied_usage_right,
	approval,
	approval_status,
	ascribable_state,
	ascribable_state_relationship,
	assembly_component_usage_substitute,
	assignment_object_relationship,
	breakdown_of,
	calendar_date,
	certification,
	certification_item,
	change_group,
	characterized_class,
	characterized_object,
	class,
	class_system,
	classification_item,
	condition,
	conditional_effectivity,
	configuration_design,
	configuration_effectivity,
	configuration_item,
	configuration_item_relationship,
	configured_effectivity_assignment,
	contract,
	date_and_time,
	date_and_time_assignment,
	date_assignment,
	dimensional_location,
	dimensional_size,
	directed_action_assignment,
	directed_dimensional_location,
	document_file,
	document_reference_item,
	document_relationship,
	document_type,
	draughting_model,
	drawing_revision,
	effectivity,
	effectivity_relationship,
	evaluated_characteristic,
	evaluated_characteristic_of_product_as_individual_test_result,
	event_occurrence,
	evidence,
	exclusive_product_concept_feature_category,
	executed_action,
	frozen_assignment,
	general_property,
	general_property_relationship,
	group,
	group_relationship,
	hierarchical_interface_connection,
	identification_assignment_relationship,
	identification_item,
	inclusion_product_concept_feature,
	information_right,
	information_usage_right,
	interface_connection,
	interface_connector_as_planned,
	interface_connector_as_realized,
	interface_connector_design,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_version,
	material_designation,
	material_designation_characterization,
	measure_representation_item,
	mechanical_design_geometric_presentation_representation,
	observation_consequence,
	organization,
	organization_relationship,
	organizational_address,
	organizational_project,
	organizational_project_relationship,
	package_product_concept_feature,
	person,
	person_and_organization,
	person_and_organization_address,
	presentation_area,
	process_operation,
	process_plan,
	product,
	product_category,
	product_class,
	product_concept,
	product_concept_feature,
	product_concept_feature_association,
	product_concept_feature_category,
	product_concept_feature_category_usage,
	product_concept_relationship,
	product_definition,
	product_definition_element_relationship,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition_group_assignment,
	product_definition_occurrence,
	product_definition_relationship,
	product_definition_substitute,
	product_definition_usage,
	product_group,
	product_group_membership,
	product_group_relationship,
	product_identification,
	product_process_plan,
	product_related_product_category,
	product_relationship,
	property_definition,
	property_definition_relationship,
	property_definition_representation,
	representation,
	representation_item,
	representation_relationship,
	requirement_assigned_item,
	requirement_assignment,
	requirement_for_action_resource,
	requirement_view_definition_relationship,
	resource_property,
	retention,
	rule_set,
	security_classification,
	security_classification_level,
	shape_aspect,
	shape_aspect_relationship,
	shape_representation,
	state_observed,
	state_observed_assignment,
	state_observed_relationship,
	state_type,
	state_type_assignment,
	state_type_relationship,
	structured_message,
	usage_association,
	validation,
	value_representation_item,
	verification,
	versioned_action_request,
	versioned_action_request_relationship );
  END_TYPE;
  
  TYPE observation_recorder_item_242 = SELECT BASED_ON observation_recorder_item WITH
  	(applied_organization_assignment,
	applied_person_and_organization_assignment);
  END_TYPE;

  TYPE ap242_position_in_organization_group_item = SELECT BASED_ON position_in_organization_group_item WITH
  (product_definition_formation);
END_TYPE;

TYPE ap242_person_type_item = SELECT BASED_ON person_type_item WITH
  (analysis_assignment);
END_TYPE;
  
  ENTITY cc_design_approval
    SUBTYPE OF (approval_assignment);
      items : SET[1:?] OF approved_item;
  END_ENTITY;

  ENTITY cc_design_certification
    SUBTYPE OF (certification_assignment);
      items : SET[1:?] OF certified_item;
  END_ENTITY;

  ENTITY cc_design_contract
    SUBTYPE OF (contract_assignment);
      items : SET[1:?] OF contracted_item;
  END_ENTITY;

  ENTITY cc_design_date_and_time_assignment
    SUBTYPE OF (date_and_time_assignment);
      items : SET[1:?] OF date_time_item;
  END_ENTITY;

  ENTITY cc_design_person_and_organization_assignment
    SUBTYPE OF (person_and_organization_assignment);
      items : SET[1:?] OF cc_person_organization_item;
    WHERE
      WR1: cc_design_person_and_organization_correlation(SELF);
  END_ENTITY;

  ENTITY cc_design_security_classification
    SUBTYPE OF (security_classification_assignment);
      items : SET[1:?] OF cc_classified_item;
  END_ENTITY;

  ENTITY cc_design_specification_reference
    SUBTYPE OF (document_reference);
      items : SET[1:?] OF cc_specified_item;
  END_ENTITY;

  ENTITY change
    SUBTYPE OF (action_assignment);
      items : SET[1:?] OF work_item;
  END_ENTITY;

  ENTITY change_request
    SUBTYPE OF (action_request_assignment);
      items : SET[1:?] OF change_request_item;
  END_ENTITY;

  ENTITY design_context
    SUBTYPE OF (product_definition_context);
    WHERE
      WR1: SELF.life_cycle_stage = 'design';
  END_ENTITY;

  ENTITY design_make_from_relationship
    SUBTYPE OF (product_definition_relationship);
  END_ENTITY;

  ENTITY mechanical_context
    SUBTYPE OF (product_context);
    WHERE
      WR1: SELF.discipline_type = 'mechanical';
  END_ENTITY;

  ENTITY start_request
    SUBTYPE OF (action_request_assignment);
      items : SET[1:?] OF start_request_item;
  END_ENTITY;

  ENTITY start_work
    SUBTYPE OF (action_assignment);
      items : SET[1:?] OF work_item;
  END_ENTITY;

  ENTITY supplied_part_relationship
    SUBTYPE OF (product_definition_relationship);
  END_ENTITY;

ENTITY mated_part_relationship
  SUBTYPE OF (group, group_assignment, product_definition_shape, product_definition_relationship, shape_aspect);
  items : SET [0:?] OF product_definition;
DERIVE
  SELF\group_assignment.assigned_group : mated_part_relationship := SELF;
  SELF\property_definition.definition : mated_part_relationship := SELF;
  SELF\shape_aspect.of_shape : mated_part_relationship := SELF;
END_ENTITY;

(*
Add following per bug #6524.
Jochen H. to review 409 related items.

Once agreed, layout will be updated.
*)
--for ENTITY 'angle_direction_reference'
  ENTITY angle_direction_reference
    SUBTYPE OF ( representation_item_relationship, geometric_representation_item );
      SELF\representation_item_relationship.relating_representation_item : orientation_basis_select;
      SELF\representation_item_relationship.related_representation_item : angle_direction_reference_select;
    WHERE
      WR1: ('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.POINT_PATH' IN TYPEOF( related_representation_item ))
      AND ('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.MIN_AND_MAJOR_PLY_ORIENTATION_BASIS' IN TYPEOF(relating_representation_item ) )  OR
        NOT ('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.POINT_PATH' IN TYPEOF( related_representation_item )) AND
           ('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.AXIS2_PLACEMENT_3D' IN TYPEOF( relating_representation_item ));
  END_ENTITY;

  ENTITY min_and_major_ply_orientation_basis
    SUBTYPE OF ( representation_item_relationship, geometric_representation_item );
      SELF\representation_item_relationship.relating_representation_item : axis2_placement_3d;
      SELF\representation_item_relationship.related_representation_item : axis2_placement_3d;
    DERIVE
      major_orientation_basis  : axis2_placement_3d := SELF\representation_item_relationship.related_representation_item;
      minor_orientation_basis  : axis2_placement_3d := SELF\representation_item_relationship.relating_representation_item;
  END_ENTITY;


  TYPE orientation_basis_select = SELECT
    ( axis2_placement_3d,
     min_and_major_ply_orientation_basis );
  END_TYPE;

TYPE angle_direction_reference_select = SELECT
    ( direction,
     curve,
     point_path );
  END_TYPE;

  TYPE angle_direction_reference_with_a2p3d_select = SELECT
    ( angle_direction_reference_select,
     axis2_placement_3d );
  END_TYPE;
  
ENTITY ap242_assignment_object_relationship
	SUBTYPE of (assignment_object_relationship);
	SELF\assignment_object_relationship.related  : ap242_assignment_object_select;									
	SELF\assignment_object_relationship.relating : ap242_assignment_object_select;									
END_ENTITY;

  ENTITY draped_defined_transformation
    SUBTYPE OF ( transformation_with_derived_angle );
  END_ENTITY;

  ENTITY laid_defined_transformation
    SUBTYPE OF ( transformation_with_derived_angle );
  END_ENTITY;

  ENTITY point_path
    SUBTYPE OF ( compound_representation_item, geometric_representation_item );
      SELF\compound_representation_item.item_element : point_path_members;
  END_ENTITY;

 TYPE point_path_members = LIST [1 : ?] OF point_and_vector;
  END_TYPE;

(*
  ENTITY point_and_vector
    SUBTYPE OF ( compound_representation_item, geometric_representation_item );
      SELF\compound_representation_item.item_element : point_and_vector_members;
  END_ENTITY;

  TYPE point_and_vector_members = LIST [2 : 3] OF point_and_vector_member;
  END_TYPE;

  TYPE point_and_vector_member = SELECT
    ( point,
     direction );
  END_TYPE;
*)
  ENTITY transformation_with_derived_angle
    SUPERTYPE OF (ONEOF (draped_defined_transformation,
            laid_defined_transformation))
    SUBTYPE OF (item_defined_transformation);
      SELF\item_defined_transformation.transform_item_1 : angle_direction_reference_with_a2p3d_select;
      SELF\item_defined_transformation.transform_item_2 : axis2_placement_3d;
    DERIVE
      orientation_angle  : plane_angle_measure := derive_angle(SELF\item_defined_transformation.transform_item_1,
                                                              SELF\item_defined_transformation.transform_item_2);
    WHERE
      WR1: (SELF\item_defined_transformation.transform_item_1\axis2_placement_3d.p[3].direction_ratios[1] =
            SELF\item_defined_transformation.transform_item_2\axis2_placement_3d.p[3].direction_ratios[1]) AND
           (SELF\item_defined_transformation.transform_item_1\axis2_placement_3d.p[3].direction_ratios[2] =
            SELF\item_defined_transformation.transform_item_2\axis2_placement_3d.p[3].direction_ratios[2]) AND
           (SELF\item_defined_transformation.transform_item_1\axis2_placement_3d.p[3].direction_ratios[3] =
            SELF\item_defined_transformation.transform_item_2\axis2_placement_3d.p[3].direction_ratios[3]);
  END_ENTITY;

  FUNCTION derive_angle(
               placement_1, placement_2 : axis2_placement_3d
           ) : plane_angle_measure;

    LOCAL
      v1     : direction;
      v2     : direction;
      mag_v1 : REAL;
      mag_v2 : REAL;
      theta  : plane_angle_measure;
    END_LOCAL;
    v1 := placement_1.p[1];
    v2 := placement_2.p[1];
    mag_v1 := SQRT( ( v1.direction_ratios[1] * v1.direction_ratios[1] ) + ( v1.direction_ratios[2] * v1.direction_ratios[2] ) );
    mag_v2 := SQRT( ( v2.direction_ratios[1] * v2.direction_ratios[1] ) + ( v2.direction_ratios[2] * v2.direction_ratios[2] ) );
    IF ( mag_v1 = 0 ) OR ( mag_v2 = 0 ) THEN
      theta := 0;
      RETURN( theta );
    END_IF;
    theta := ACOS( ( ( v1.direction_ratios[1] * v2.direction_ratios[1] ) + ( v1.direction_ratios[2] * v2.direction_ratios[2] ) )
        / ( mag_v1 * mag_v2 ) );
    RETURN( theta );
  END_FUNCTION;
--end items added for bug 6524

SUBTYPE_CONSTRAINT ap242_founded_item_subtypes FOR founded_item;
  ABSTRACT SUPERTYPE;
  ONEOF (b_spline_curve_knot_locator,
         b_spline_curve_segment,
         b_spline_surface_knot_locator,
         b_spline_surface_patch,
         b_spline_surface_strip,
         boundary_curve_of_b_spline_or_rectangular_composite_surface,
         box_domain,
         character_glyph_style_outline,
         character_glyph_style_stroke,
         composite_curve_segment,
         composite_curve_transition_locator,
         curve_style,
         curve_style_font,
         curve_style_font_and_scaling,
         curve_style_font_pattern,
         externally_defined_style,
         fill_area_style,
         interpolated_configuration_segment,
         kinematic_path_segment,
         plane_angle_and_length_pair,
         plane_angle_and_ratio_pair,
         point_style,
         presentation_style_assignment,
         rectangular_composite_surface_transition_locator,
         surface_patch,
         surface_side_style,
         surface_style_boundary,
         surface_style_control_grid,
         surface_style_fill_area,
         surface_style_parameter_line,
         surface_style_segmentation_curve,
         surface_style_silhouette,
         surface_style_usage,
         symbol_style,
         text_style,
         view_volume);
END_SUBTYPE_CONSTRAINT;

--bug 8532
RULE ap242_subtype_mandatory_shape_representation FOR (application_context, shape_representation);

WHERE
  WR1: NOT( SIZEOF( QUERY( ac <* application_context |
              (SIZEOF (QUERY (apd <* USEDIN(ac,'APPLICATION_CONTEXT_SCHEMA.APPLICATION_PROTOCOL_DEFINITION.APPLICATION') |
                apd.application_interpreted_model_schema_name = 'ap242_managed_model_based_3d_engineering_mim_lf'
                )) > 0)
              )) > 0) OR
       (SIZEOF (QUERY (sr <* shape_representation |
       NOT ((SIZEOF (ap242_shape_representation_reference_types * TYPEOF (sr)) = 1) OR
       (SIZEOF (QUERY (it <* sr\representation.items |
       NOT ('GEOMETRY_SCHEMA.AXIS2_PLACEMENT_3D' IN TYPEOF (it))))
       = 0) OR
       (SIZEOF (QUERY (sdr <* QUERY (pdr <* USEDIN (sr,
       'PRODUCT_PROPERTY_REPRESENTATION_SCHEMA.PROPERTY_DEFINITION_REPRESENTATION.' +
       'USED_REPRESENTATION') |
       'PRODUCT_PROPERTY_REPRESENTATION_SCHEMA.SHAPE_DEFINITION_REPRESENTATION' IN
       TYPEOF (pdr)) |
       NOT (SIZEOF (['PRODUCT_PROPERTY_DEFINITION_SCHEMA.SHAPE_ASPECT',
       'PRODUCT_PROPERTY_DEFINITION_SCHEMA.SHAPE_ASPECT_RELATIONSHIP'] * TYPEOF
       (sdr.definition)) = 1))) = 0)))) = 0);
END_RULE; -- subtype_mandatory_shape_representation

  RULE dimensioning_data_requires_document FOR (applied_document_reference, product_definition_context_association, role_association);
    LOCAL
      adr : SET OF applied_document_reference := (QUERY(adr <* applied_document_reference |
                         (adr\document_reference.assigned_document\document.kind\document_type.product_data_type = 'Standards Document') AND
                         ((adr\document_reference.assigned_document\document.id = 'ASME Y14.41-2003') OR
                         (adr\document_reference.assigned_document\document.id = 'ASME Y14.5M-1994') OR
                         (adr\document_reference.assigned_document\document.id = 'ISO 1101: 2004'))));
      pdca : SET OF product_definition_context_association := (QUERY(pdca <* product_definition_context_association |
                         (pdca\product_definition_context_association.role\product_definition_context_role.name = 'additional context') AND
                         (pdca\product_definition_context_association.frame_of_reference\application_context_element.name = 'Geometric Dimensioning and Tolerancing Product Specification')));
      ra : SET OF role_association := (QUERY(ra <* role_association |
                         ra\role_association.role\object_role.name = 'dimensioning standard'));
      ra1 : SET OF role_association := [];
      pdpdca : SET OF product_definition := [];
      pdadr : SET OF product_definition := [];
      pass : BOOLEAN := TRUE;
    END_LOCAL;

    REPEAT i := 1 TO HIINDEX(pdca);
       pdpdca := pdpdca + pdca[i]\product_definition_context_association.definition;
    END_REPEAT;
    REPEAT i := 1 TO HIINDEX(adr);
       ra1 := bag_to_set(USEDIN(adr[i],'BASIC_ATTRIBUTE_SCHEMA.ROLE_ASSOCIATION.ITEM_WITH_ROLE'));
       IF (ra1 * ra) <> ra1 THEN
        pass := FALSE;
       END_IF;
      REPEAT j := 1 to HIINDEX(adr[i]\applied_document_reference.items);
       IF 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION' IN TYPEOF(adr[i]\applied_document_reference.items[j]) THEN
        pdadr := pdadr + adr[i]\applied_document_reference.items[j];
       END_IF;
      END_REPEAT;
    END_REPEAT;

    WHERE
     WR1 : pass;
     WR2 : pdpdca = pdadr;

END_RULE;

  RULE ap242_application_protocol_definition_required FOR
      (application_context);
    WHERE
      WR1:  SIZEOF( QUERY( ac <* application_context |
              (SIZEOF (QUERY (apd <* USEDIN(ac,'APPLICATION_CONTEXT_SCHEMA.APPLICATION_PROTOCOL_DEFINITION.APPLICATION') |
                apd.application_interpreted_model_schema_name = 'ap242_managed_model_based_3d_engineering_mim_lf'
                )) > 0)
              )) > 0;

  END_RULE;

RULE valid_product_and_manufacturing_information_view_contexts FOR (product_definition_context);
LOCAL
  design_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.life_cycle_stage = 'design');
  gdt_representation_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'geometrical dimensioning and tolerancing representation');
  machining_feature_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'machining feature');
  material_specification_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'material specification');
  model_based_3d_annotation_presentation_view_contexts  : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'model based 3D annotation presentation');
  model_based_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'model based product geometry');
  process_state_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'process state');
  surface_finish_view_contexts : SET OF product_definition_context :=
    QUERY( pdc <* product_definition_context | pdc.frame_of_reference.application = 'surface finish');
  additional_view_contexts : SET OF product_definition_context :=
         gdt_representation_view_contexts + machining_feature_view_contexts + material_specification_view_contexts +
         model_based_3d_annotation_presentation_view_contexts + process_state_view_contexts + surface_finish_view_contexts;
  need_initial_model_based_view_contexts : SET OF product_definition_context :=
    gdt_representation_view_contexts + model_based_3d_annotation_presentation_view_contexts;
END_LOCAL;

WHERE
  WR1: SIZEOF(gdt_representation_view_contexts * design_view_contexts) = SIZEOF(gdt_representation_view_contexts);
  WR2: SIZEOF(machining_feature_view_contexts * design_view_contexts) = SIZEOF(machining_feature_view_contexts);
  WR3: SIZEOF(material_specification_view_contexts * design_view_contexts) = SIZEOF(material_specification_view_contexts);
  WR4: SIZEOF(model_based_3d_annotation_presentation_view_contexts * design_view_contexts) = SIZEOF(model_based_3d_annotation_presentation_view_contexts);
  WR5: SIZEOF(model_based_view_contexts * design_view_contexts) = SIZEOF(model_based_view_contexts);
  WR6: SIZEOF(process_state_view_contexts * design_view_contexts) = SIZEOF(process_state_view_contexts);
  WR7: SIZEOF(surface_finish_view_contexts * design_view_contexts) = SIZEOF(surface_finish_view_contexts);
  WR8: -- not used as additional_contexts
       SIZEOF(QUERY(mbvc <* model_based_view_contexts |
        (SIZEOF(USEDIN(mbvc, 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION_CONTEXT_ASSOCIATION.FRAME_OF_REFERENCE')) = 0)
        )) = SIZEOF(model_based_view_contexts);
  WR9: -- not used as initial_context
       SIZEOF(QUERY(avc <* additional_view_contexts |
        (SIZEOF(USEDIN(avc, 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION.FRAME_OF_REFERENCE')) = 0)
       )) = SIZEOF(additional_view_contexts);
  WR10: -- initial_context shall have a Model_based_view_context
       SIZEOF(QUERY(nimbvc <* need_initial_model_based_view_contexts | NOT
        (SIZEOF(QUERY(pdca <* USEDIN(nimbvc, 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION_CONTEXT_ASSOCIATION.FRAME_OF_REFERENCE') |
         (pdca\product_definition_context_association.definition\product_definition.frame_of_reference IN model_based_view_contexts)))
        =
        SIZEOF(need_initial_model_based_view_contexts))
       )) = 0;
  WR11:  -- gdt_representation_view_contexts must have at least either ISO 1101 or ASME Y14.5 as associated dimension standard document
	SIZEOF ( QUERY( gdt_pdc <* gdt_representation_view_contexts |
  	         	SIZEOF(['ISO 1101', 'ASME Y14.5'] * get_associated_mandatory_document_ids(gdt_pdc) ) = 0 )
  	       ) = 0;
  WR12: -- model_based_3d_annotation_presentation_view_contexts must have at least either ISO 1101, ISO 16792, ASME Y14.41 or ASME Y14.5 as associated model standard document
	SIZEOF ( QUERY( mb3d_pdc <* model_based_3d_annotation_presentation_view_contexts |
  	             SIZEOF(['ISO 1101', 'ISO 16792', 'ASME Y14.41', 'ASME Y14.5'] * get_associated_mandatory_document_ids(mb3d_pdc) ) = 0)
  	       ) = 0;
END_RULE;

FUNCTION get_associated_mandatory_document_ids(pdc : product_definition_context) : SET OF STRING;
	LOCAL
		result : SET OF STRING := [];
		adrs_raw : SET OF applied_document_reference := bag_to_set(USEDIN(pdc, 'DOCUMENT_ASSIGNMENT_MIM.APPLIED_DOCUMENT_REFERENCE.ITEMS'));
		adrs_filtered : SET OF applied_document_reference := [];
		ras : SET OF role_association;
		dpas : SET OF document_product_association;
	END_LOCAL;

	-- scan adrs_raw for associated role 'mandatory' and fill adrs_filtered with results
	REPEAT i := 1 TO HIINDEX(adrs_raw);
		if adrs_raw[i]\document_reference.role\object_role.name = 'mandatory' THEN
			adrs_filtered := adrs_filtered + adrs_raw[i];
		END_IF;
	END_REPEAT;

	-- scan through adrs_filtered and access associated product.id s
	REPEAT i := 1 TO HIINDEX(adrs_filtered);
		dpas := bag_to_set(USEDIN(adrs_filtered[i]\document_reference.assigned_document, 'DOCUMENT_SCHEMA.DOCUMENT_PRODUCT_ASSOCIATION.RELATING_DOCUMENT'));
		REPEAT j := 1 TO HIINDEX(dpas);
			IF 'DOCUMENT_ASSIGNMENT_MIM.DOCUMENT_PRODUCT_EQUIVALENCE' IN TYPEOF (dpas[j]) THEN
			   IF 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION_FORMATION' IN TYPEOF (dpas[j]\document_product_association.related_product) THEN
			   		result := result + dpas[j]\document_product_association.related_product\product_definition_formation.of_product\product.id;
			   END_IF;
			   IF 'PRODUCT_DEFINITION_SCHEMA.PRODUCT' IN TYPEOF (dpas[j].related_product) THEN
			   		result := result + dpas[j]\document_product_association.related_product\product.id;
			   END_IF;
			END_IF;
		END_REPEAT;
	END_REPEAT;

	RETURN (result);
END_FUNCTION;

  FUNCTION cc_design_person_and_organization_correlation
   (e : cc_design_person_and_organization_assignment) : BOOLEAN;
    LOCAL
      po_role : STRING;
    END_LOCAL;
      po_role := e\person_and_organization_assignment.role.name;
    CASE po_role OF
      'request_recipient'      : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF(['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_REQUEST'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN(FALSE);
                               END_IF;
      'initiator'              : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF(['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_WORK',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN(FALSE);
                               END_IF;
      'creator'                : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF (['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN (FALSE);
                               END_IF;
      'part_supplier'          : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'design_supplier'        : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'design_owner'           : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.PRODUCT'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'configuration_manager'  : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CONFIGURATION_ITEM'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'contractor'             : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.CONTRACT'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'classification_officer' : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'SECURITY_CLASSIFICATION'
                                 IN TYPEOF (x))) THEN
                                 RETURN(FALSE);
                               END_IF;
    OTHERWISE : RETURN(TRUE);
  END_CASE;
  RETURN (TRUE);
  END_FUNCTION;

END_SCHEMA;
