(*
   Part1000: $Id: $
 STEPmod.CVS.Id: arm.exp,v 1.21 2019/04/18 13:14:26 verodub Exp
   ISO TC184/SC4/WG12 N10393 - ISO/TS 10303-1025 Alias identification - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N5275
*)

SCHEMA Alias_identification_arm;

USE FROM Identification_assignment_arm;   -- ISO/TS 10303-1021

  ENTITY Alias_identification
    SUBTYPE OF (Identification_assignment);
    DERIVE
      SELF\Identification_assignment.role : STRING := 'alias';
  END_ENTITY;

END_SCHEMA;

