(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.3 2015/09/24 11:01:19 lothartklein Exp
   ISO TC184/SC4/WG12 N7925 - ISO/TS 10303-1813 Parametric representation - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7362
*)

SCHEMA Parametric_representation_mim;

USE FROM Foundation_representation_mim; --  ISO/TS 10303-1006
USE FROM representation_schema( -- ISO 10303-43
  definitional_representation,
  parametric_representation_context);

END_SCHEMA;
